version: "0.2"
language: en

words:
  - absolutize
  - absolutized
  - absolutizes
  - arktype
  - begincolumn
  - beginline
  - buildid
  - compoundassign
  - covmap
  - debugname
  - defu
  - difftime
  - dndebug
  - doublestar
  - elseBlock
  - elseExpr
  - elsebody
  - elseifs
  - emcc
  - emscripten
  - emsdk
  - emxx
  - endcolumn
  - fmod
  - foreachi
  - frexp
  - fwasm
  - getmetatable
  - getn
  - gmatch
  - gsub
  - highlightjs
  - indexexpr
  - injective
  - instrumentability
  - instrumentable
  - instrumenter
  - interp
  - interpolatedstring
  - interpstring
  - ipairs
  - ldexp
  - lhsOperand
  - localfunction
  - materializer
  - maxn
  - misresolution
  - modf
  - mountless
  - newproxy
  - ocale
  - pcall
  - pnpmfile
  - pnpmfiles
  - randomseed
  - rawequal
  - rawget
  - rawlen
  - rawset
  - rbxl
  - rbxlx
  - rbxm
  - rbxmx
  - recognised
  - rhsOperand
  - rojo
  - setmetatable
  - statfunction
  - statlocalfunction
  - thenBlock
  - thenExpr
  - thenbody
  - typealias
  - typeassertion
  - typefunction
  - uncompiled
  - unmappable
  - unparseable
  - unprobed
  - unrecognised
  - unstub
  - upgraders
  - vararg
  - varargs
  - writeback
  - xpcall
