packages:
  - packages/*

overrides:
  "@typescript-eslint/eslint-plugin": 8.62.1
  "@typescript-eslint/parser": 8.62.1
  "@typescript-eslint/type-utils": 8.62.1
  "@typescript-eslint/types": 8.62.1
  "@typescript-eslint/typescript-estree": 8.62.1
  "@typescript-eslint/utils": 8.62.1

minimumReleaseAgeExclude:
  - "@bedrock-rbx/ocale"
  - "@isentinel/eslint-config"
  - "@rolldown/binding-darwin-arm64@1.2.7"
  - "@rolldown/binding-linux-ppc64-gnu@1.2.7"

publicHoistPattern:
  - "*@rbxts*"
  - "@typescript/*"

patchedDependencies:
  "@stryker-mutator/vitest-runner@10.0.0": patches/@stryker-mutator__vitest-runner@10.0.0.patch
