import { fromAny } from "@total-typescript/shoehorn";

import * as path from "node:path";
import { describe, expect, it, vi } from "vitest";

import { createMemoryFileSystem } from "../../test/mocks/memory-file-system.ts";
import type { ResolvedProjectConfig } from "../config/projects.ts";
import { DEFAULT_CONFIG, type ResolvedConfig } from "../config/schema.ts";
import { STUB_FILENAME } from "../config/stubs.ts";
import type { PrepareCoverageResult } from "../coverage-pipeline/prepare.ts";
import {
	COVERAGE_BUILD_MANIFEST_PATH,
	COVERAGE_MANIFEST_PATH,
} from "../coverage-pipeline/prepare.ts";
import type { RunDispatch } from "../run.ts";
import type { RunSeams } from "../run/seams.ts";
import { nodeRunSeams } from "../run/seams.ts";
import type { FileSystem } from "../utils/file-system.ts";
import { buildCoveragePlaceAsync } from "./build-coverage-place.ts";

const ROOT_DIR = "/test";
const MOUNT_FS_PATH = "out/shared";
const MOUNT_DATA_MODEL_PATH = "ReplicatedStorage/shared";
const CACHE_STUB_PATH = path.resolve(ROOT_DIR, ".jest-roblox/cache", MOUNT_FS_PATH, STUB_FILENAME);
const LEFTOVER_STUB_PATH = path.resolve(ROOT_DIR, MOUNT_FS_PATH, STUB_FILENAME);
const GENERATED_STUB = "-- Auto-generated by jest-roblox (do not edit)\nreturn {}\n";

const COVERAGE_PLACE = { hash: "cov-hash", path: ".jest-roblox/coverage/game.rbxl" };

interface Harness {
	dispatch: RunDispatch;
	fileSystem: FileSystem;
	seams: RunSeams;
}

function makeConfig(overrides: Partial<ResolvedConfig> = {}): ResolvedConfig {
	return {
		...DEFAULT_CONFIG,
		rootDir: ROOT_DIR,
		testMatch: ["**/*.spec.ts"],
		testPathIgnorePatterns: [],
		...overrides,
	};
}

function makeProject(): ResolvedProjectConfig {
	return fromAny({
		config: {},
		displayName: "main",
		include: ["src/**/*.spec.ts"],
		projects: [MOUNT_DATA_MODEL_PATH],
		rojoMounts: [{ dataModelPath: MOUNT_DATA_MODEL_PATH, fsPath: MOUNT_FS_PATH }],
		testMatch: ["**/*.spec.ts"],
	});
}

function makeCoverageResult(rebuilt: boolean): PrepareCoverageResult {
	return fromAny({
		buildId: "build-77",
		coveragePlace: COVERAGE_PLACE,
		files: {},
		instrumentMs: 0,
		manifest: { generatedAt: "2026-06-07T00:00:00.000Z" },
		placeFile: COVERAGE_PLACE.path,
		rebuilt,
		stagingMs: 0,
	});
}

const MANIFEST_PROJECT = {
	displayName: "main",
	projectDataModelPath: MOUNT_DATA_MODEL_PATH,
	setupFiles: [],
	setupFilesAfterEnv: [],
	testMatch: ["**/*.spec.ts"],
};

function seed(rebuilt = true): Harness {
	const { fileSystem } = createMemoryFileSystem({
		[LEFTOVER_STUB_PATH]: GENERATED_STUB,
		[path.resolve(ROOT_DIR, MOUNT_FS_PATH, "init.luau")]: "return {}",
	});
	const dispatch: RunDispatch = {
		buildImplicitProject: vi
			.fn<RunDispatch["buildImplicitProject"]>()
			.mockReturnValue(makeProject()),
		loadRojoTree: vi
			.fn<RunDispatch["loadRojoTree"]>()
			.mockReturnValue(fromAny({ $className: "DataModel" })),
		runMultiProject: vi.fn<RunDispatch["runMultiProject"]>(),
		runResolvedProjects: vi.fn<RunDispatch["runResolvedProjects"]>(),
		runWorkspaceMode: vi.fn<RunDispatch["runWorkspaceMode"]>(),
	};
	const seams: RunSeams = {
		...nodeRunSeams(),
		prepareCoverage: vi
			.fn<RunSeams["prepareCoverage"]>()
			.mockResolvedValue(makeCoverageResult(rebuilt)),
		resolveAllProjects: vi.fn<RunSeams["resolveAllProjects"]>().mockResolvedValue([]),
	};
	return { dispatch, fileSystem, seams };
}

function readBuildManifest({ fileSystem }: Harness): {
	cleanPlace?: unknown;
	coveragePlace: unknown;
} {
	return fromAny(JSON.parse(fileSystem.readFileSync(COVERAGE_BUILD_MANIFEST_PATH, "utf8")));
}

describe(buildCoveragePlaceAsync, () => {
	it("should return the coverage place, build id, and manifest paths", async () => {
		expect.assertions(1);

		const harness = seed();

		const bundle = await buildCoveragePlaceAsync(makeConfig(), harness);

		expect(bundle).toStrictEqual({
			buildId: "build-77",
			buildManifestPath: COVERAGE_BUILD_MANIFEST_PATH,
			coverageManifestPath: COVERAGE_MANIFEST_PATH,
			coveragePlace: COVERAGE_PLACE,
			projects: [MANIFEST_PROJECT],
			rebuilt: true,
		});
	});

	it("should force coverage collection on regardless of the input config", async () => {
		expect.assertions(1);

		const harness = seed();

		await buildCoveragePlaceAsync(makeConfig({ collectCoverage: false }), harness);

		const [config] = vi.mocked(harness.seams.prepareCoverage).mock.calls[0]!;

		expect(config.collectCoverage).toBeTrue();
	});

	it("should emit the build manifest with the coverage place and no clean place", async () => {
		expect.assertions(2);

		const harness = seed();

		await buildCoveragePlaceAsync(makeConfig(), harness);

		const manifest = readBuildManifest(harness);

		expect(manifest.coveragePlace).toStrictEqual(COVERAGE_PLACE);
		expect(manifest.cleanPlace).toBeUndefined();
	});

	it("should always bake jest.config stubs so the place is self-contained", async () => {
		expect.assertions(3);

		const harness = seed();

		await buildCoveragePlaceAsync(makeConfig(), harness);

		expect(harness.fileSystem.existsSync(LEFTOVER_STUB_PATH)).toBeFalse();
		expect(harness.fileSystem.existsSync(CACHE_STUB_PATH)).toBeTrue();
		// `bakeStubs` is always true on this path: a place handed to a foreign
		// runner has to be self-contained.
		expect(vi.mocked(harness.seams.prepareCoverage).mock.calls[0]![1]!.bake).toBeDefined();
	});

	it.for([undefined, []])(
		"should resolve the implicit project for projects=%j",
		async (projects) => {
			expect.assertions(2);

			const harness = seed();

			await buildCoveragePlaceAsync(makeConfig({ projects }), harness);

			expect(harness.dispatch.buildImplicitProject).toHaveBeenCalledOnce();
			expect(harness.seams.resolveAllProjects).not.toHaveBeenCalled();
		},
	);

	it("should resolve declared projects in multi mode", async () => {
		expect.assertions(2);

		const harness = seed();
		vi.mocked(harness.seams.resolveAllProjects).mockResolvedValue([makeProject()]);

		await buildCoveragePlaceAsync(
			makeConfig({ projects: [fromAny({ test: { displayName: "c" } })] }),
			harness,
		);

		expect(harness.seams.resolveAllProjects).toHaveBeenCalledOnce();
		expect(harness.dispatch.buildImplicitProject).not.toHaveBeenCalled();
	});

	it("should not rewrite the build manifest on the incremental no-change reuse path", async () => {
		expect.assertions(2);

		const harness = seed(false);

		const bundle = await buildCoveragePlaceAsync(makeConfig(), harness);

		expect(harness.fileSystem.existsSync(COVERAGE_BUILD_MANIFEST_PATH)).toBeFalse();
		expect(bundle.rebuilt).toBeFalse();
	});
});
