import * as fs from "node:fs";
import * as path from "node:path";
import { describe, expect, it } from "vitest";

import { startFakeOpenCloudServerAsync } from "./fake-open-cloud.ts";
import {
	buildPassingJestOutput,
	createFixtureSandbox,
	createOpenCloudEnvironment,
	rojoOnPath,
	runCliAsync,
} from "./helpers.ts";

const LUAU_FIXTURE_PATH = path.resolve(__dirname, "../fixtures/luau-project");
const RUN_TIMEOUT_MS = 60_000;

// Regression: a bare `test:` config with no `projects` must run end to end. It
// collapses into the multi pipeline, where one project is synthesized from the
// config's Luau roots mapped through the Rojo tree. The Luau runner resolves
// per-project config from a `jest.config` ModuleScript at each root — which a
// bare config never supplied, so before the synthesized project carried a
// generated stub the run reached Roblox and died there.
//
// Everything that decides whether the stub exists and where it goes is local:
// the synthesized project list, the emitted cache stub, and the place actually
// being built and dispatched. Those are what this asserts, against the fake
// backend. That the Luau runner then reads an injected stub is the same code
// path the live both-mounts run in `test/e2e/live/pipeline.e2e.spec.ts`
// exercises, so it is not worth a second place upload here.
describe("bare no-projects config", () => {
	it.skipIf(!rojoOnPath())(
		"should synthesize a project from the rojo tree and give it a generated stub",
		async () => {
			expect.assertions(8);

			const sandbox = createFixtureSandbox(LUAU_FIXTURE_PATH);
			// The stub the runner requires, at the synthesized project's mount.
			// Canonical location is the cache; the source tree stays clean.
			const cacheStubPath = path.join(sandbox, ".jest-roblox/cache/src/jest.config.luau");

			// Asserted before the run, not just after. `.jest-roblox/` is a
			// gitignored run artifact, and the specs that drive the CLI at a
			// fixture path rather than a sandbox leave one behind — so on a
			// machine where those ran first, a sandbox that copied it would
			// satisfy every assertion below with stub generation fully broken.
			// `createFixtureSandbox` filters it out; this is the check that says
			// so, and it fails loudly if the filter ever stops working.
			expect(fs.existsSync(cacheStubPath), "sandbox starts with no stub").toBeFalse();

			const server = await startFakeOpenCloudServerAsync([
				{ jestOutput: buildPassingJestOutput() },
			]);

			const result = await runCliAsync(["--backend", "open-cloud"], {
				cwd: sandbox,
				env: createOpenCloudEnvironment(server.baseUrl),
				timeoutMs: RUN_TIMEOUT_MS,
			});

			expect(result.exitCode, `stderr: ${result.stderr}\nstdout: ${result.stdout}`).toBe(0);
			expect(result.stdout, "the synthesized project ran its spec").toContain("1 passed");

			expect(
				fs.existsSync(cacheStubPath),
				"generated stub for the synthesized root",
			).toBeTrue();

			// The marker prefix is what makes it a *generated* stub — the
			// workspace runner's pre-flight cleanup keys off this exact string,
			// and a user-authored file must never carry it. The `displayName`
			// alongside it is the evidence that a project was synthesized at
			// all, rather than the run finding nothing to name.
			const stub = fs.readFileSync(cacheStubPath, "utf-8");

			expect(stub, "stub is generated, not user-authored").toStartWith(
				"-- Auto-generated by jest-roblox (do not edit)\n",
			);
			expect(stub, "stub carries the synthesized project identity").toInclude("displayName");
			expect(
				fs.existsSync(path.join(sandbox, "src/jest.config.luau")),
				"no stub in the source mount",
			).toBeFalse();

			// Guards against a short-circuit: without this, a run that discovered
			// nothing and exited 0 would satisfy the assertions above.
			expect(server.uploadCount, "place was built and dispatched").toBe(1);
		},
		RUN_TIMEOUT_MS + 5000,
	);

	// The other half of `resolveLuauRootsWithRojo`. The fixture's own config
	// names no `luauRoots`, so the case above takes the fallback that derives
	// them from the Rojo tree; this one sets them explicitly and takes the early
	// return. Both reach `buildImplicitProject`, and only the explicit branch
	// can put a root in the config that the tree does not mount — which is the
	// error the branch exists to raise.
	it.skipIf(!rojoOnPath())(
		"should synthesize from an explicit luauRoots rather than the rojo tree",
		async () => {
			expect.assertions(3);

			const sandbox = createFixtureSandbox(LUAU_FIXTURE_PATH);
			// One config, not two: the loader would otherwise have to choose
			// between the fixture's `.luau` and this `.ts`, and which wins is
			// not what this case is about.
			fs.rmSync(path.join(sandbox, "jest.config.luau"));
			fs.writeFileSync(
				path.join(sandbox, "jest.config.ts"),
				`export default ${JSON.stringify(
					{
						luauRoots: ["src"],
						rojoProject: "default.project.json",
						test: { displayName: "explicit-roots", testMatch: ["**/*.spec.luau"] },
					},
					undefined,
					"\t",
				)};\n`,
			);

			const server = await startFakeOpenCloudServerAsync([
				{ jestOutput: buildPassingJestOutput() },
			]);

			const result = await runCliAsync(["--backend", "open-cloud"], {
				cwd: sandbox,
				env: createOpenCloudEnvironment(server.baseUrl),
				timeoutMs: RUN_TIMEOUT_MS,
			});

			expect(result.exitCode, `stderr: ${result.stderr}\nstdout: ${result.stdout}`).toBe(0);

			const stub = fs.readFileSync(
				path.join(sandbox, ".jest-roblox/cache/src/jest.config.luau"),
				"utf-8",
			);

			expect(stub, "stub generated at the explicitly named root").toStartWith(
				"-- Auto-generated by jest-roblox (do not edit)\n",
			);
			expect(server.uploadCount, "place was built and dispatched").toBe(1);
		},
		RUN_TIMEOUT_MS + 5000,
	);
});
