import * as fs from "node:fs";
import * as path from "node:path";
import { describe, expect, it } from "vitest";

import { startFakeOpenCloudServerAsync } from "./fake-open-cloud.ts";
import {
	buildPassingJestOutput,
	createFixtureSandbox,
	createOpenCloudEnvironment,
	rojoOnPath,
	runCliAsync,
} from "./helpers.ts";

const USER_AUTHORED_FIXTURE_PATH = path.resolve(__dirname, "../fixtures/user-authored-config");
const RUN_TIMEOUT_MS = 60_000;

// Regression: stub-injection refactor (PR #464). Multi-project shape with
// two inline-object entries — one mount has no user-authored config, the
// other already has a `jest.config.luau` Rojo will sync. Per-mount FS
// detection via `hasUserAuthoredConfig` must gate both stub generation and
// the synthesizer's stubMount construction: the user's file at `src/b`
// stays byte-identical, no cache stub lands at `src/b`, and the inline
// entry at `src/a` still gets its generated cache stub. Unit-tested via
// mocks in `stubs.spec.ts`, but the full multi-project pipeline wiring
// has no prior e2e — direct-Luau users with a hand-authored config at one
// mount are the primary failure mode this guards.
describe("multi-project per-mount user-authored config respect", () => {
	it.skipIf(!rojoOnPath())(
		"should leave user-authored jest.config.luau untouched while generating cache stubs for mounts without user files",
		async () => {
			expect.assertions(6);

			const sandbox = createFixtureSandbox(USER_AUTHORED_FIXTURE_PATH);
			const userConfigPath = path.join(sandbox, "src/b/jest.config.luau");
			const seededUserConfig = fs.readFileSync(userConfigPath);

			const server = await startFakeOpenCloudServerAsync([
				{ jestOutput: buildPassingJestOutput(), pkg: "a", project: "a" },
				{ jestOutput: buildPassingJestOutput(), pkg: "b", project: "b" },
			]);

			const result = await runCliAsync(["--backend", "open-cloud", "--parallel=2"], {
				cwd: sandbox,
				env: createOpenCloudEnvironment(server.baseUrl),
				timeoutMs: RUN_TIMEOUT_MS,
			});

			expect(result.exitCode, `stderr: ${result.stderr}\nstdout: ${result.stdout}`).toBe(0);
			// User-authored file survives byte-for-byte — never overwritten
			// by a generated marker stub.
			expect(fs.existsSync(userConfigPath)).toBeTrue();
			expect(fs.readFileSync(userConfigPath).equals(seededUserConfig)).toBeTrue();

			// Project "a" mount has no user file → cache stub generated with
			// the load-bearing marker prefix.
			const aCacheStubPath = path.join(sandbox, ".jest-roblox/cache/src/a/jest.config.luau");

			expect(fs.existsSync(aCacheStubPath)).toBeTrue();
			expect(
				fs
					.readFileSync(aCacheStubPath, "utf-8")
					.startsWith("-- Auto-generated by jest-roblox (do not edit)\n"),
			).toBeTrue();

			// Project "b" mount has a user file → generation must skip it
			// entirely. No cache stub lands at `.jest-roblox/cache/src/b/`.
			expect(
				fs.existsSync(path.join(sandbox, ".jest-roblox/cache/src/b/jest.config.luau")),
			).toBeFalse();
		},
		RUN_TIMEOUT_MS + 5000,
	);
});
