import { fromAny } from "@total-typescript/shoehorn";

import * as path from "node:path";
import process from "node:process";
import { describe, expect, it, vi } from "vitest";

import { fakeTimingCollector, phaseNamesOf } from "../../test/mocks/fake-timing-collector.ts";
import type { MemoryVolume } from "../../test/mocks/memory-file-system.ts";
import { createMemoryFileSystem } from "../../test/mocks/memory-file-system.ts";
import type { ResolvedProjectConfig } from "../config/projects.ts";
import { STUB_FILENAME } from "../config/stubs.ts";
import type { WorkspacePackageCoverage } from "../coverage-pipeline/workspace-prepare.ts";
import type { PackageDescriptor } from "../staging/synthesizer.ts";
import type { TimedPhase, TimingCollector } from "../timing/orchestration-collector.ts";
import { toPosixRoot } from "../utils/normalize-windows-path.ts";
import type { PackageContext } from "./project-contexts.ts";
import { stageWorkspaceStubs } from "./stub-staging.ts";
import type { PendingEntry } from "./test-selection.ts";

const GENERATED_STUB = "-- Auto-generated by jest-roblox (do not edit)\nreturn {}\n";
const USER_STUB = "return { displayName = 'authored' }\n";

const COVERAGE_ROOTS = [{ luauRoot: toPosixRoot("src"), shadowDir: "/shadow/foo" }];
const COVERAGE_SPINE = [{ luauRoot: toPosixRoot("."), shadowDir: "/shadow/.spine" }];

interface StagedWorkspace {
	bar: PackageContext;
	foo: PackageContext;
	staged: TimedPhase<Array<PackageDescriptor>>;
	timing: TimingCollector;
	volume: MemoryVolume;
}

function makeProject(displayName: string, mounts = ["src/Server"]): ResolvedProjectConfig {
	return fromAny({
		config: {},
		displayName,
		rojoMounts: mounts.map((fsPath) => {
			return { dataModelPath: `ServerScriptService/${displayName}`, fsPath };
		}),
		testMatch: ["**/*.spec"],
	});
}

function makeContext(name: string, projects: Array<ResolvedProjectConfig>): PackageContext {
	const packageDirectory = path.resolve("/workspace", name);
	return fromAny({
		cacheRoot: path.resolve("/cache", name),
		descriptor: {
			name,
			packageDirectory,
			rojoProjectPath: path.resolve(packageDirectory, "default.project.json"),
		} satisfies PackageDescriptor,
		info: { name, packageDirectory },
		projects,
	});
}

function makePending(packageName: string, project: ResolvedProjectConfig): PendingEntry {
	return fromAny({ pkg: packageName, project });
}

function sourceStub(context: PackageContext, mount: string): string {
	return path.resolve(context.info.packageDirectory, mount, STUB_FILENAME);
}

function cacheStub(context: PackageContext, mount: string): string {
	return path.resolve(context.cacheRoot, mount, STUB_FILENAME);
}

function seed(volume: MemoryVolume, filePath: string, content: string): void {
	volume.mkdirSync(path.dirname(filePath), { recursive: true });
	volume.writeFileSync(filePath, content);
}

function stageTwoPackages(): StagedWorkspace {
	const client = makeProject("client");
	const dormant = makeProject("dormant", ["src/Dormant"]);
	const server = makeProject("server");
	const foo = makeContext("@halcyon/foo", [client, dormant]);
	const bar = makeContext("@halcyon/bar", [server]);
	const timing = fakeTimingCollector(12);

	const { fileSystem, volume } = createMemoryFileSystem();
	seed(volume, sourceStub(foo, "src/Server"), GENERATED_STUB);
	seed(volume, sourceStub(foo, "src/Dormant"), GENERATED_STUB);
	vi.spyOn(process.stderr, "write").mockReturnValue(true);

	const staged = stageWorkspaceStubs({
		contexts: [foo, bar],
		coverageByPackage: new Map<string, WorkspacePackageCoverage>([
			[
				"@halcyon/foo",
				fromAny({ coverageRoots: COVERAGE_ROOTS, coverageSpine: COVERAGE_SPINE }),
			],
		]),
		fileSystem,
		pending: [makePending("@halcyon/foo", client), makePending("@halcyon/bar", server)],
		timing,
	});

	return { bar, foo, staged, timing, volume };
}

describe(stageWorkspaceStubs, () => {
	it("should stage only live projects and attach coverage roots to their package", () => {
		expect.assertions(3);

		const { bar, foo, staged, timing } = stageTwoPackages();

		expect(staged.value).toStrictEqual([
			{
				...foo.descriptor,
				coverageRoots: COVERAGE_ROOTS,
				coverageSpine: COVERAGE_SPINE,
				stubMounts: [
					{
						absStubPath: cacheStub(foo, "src/Server"),
						dataModelPath: "ServerScriptService/client",
					},
				],
			},
			{
				...bar.descriptor,
				stubMounts: [
					{
						absStubPath: cacheStub(bar, "src/Server"),
						dataModelPath: "ServerScriptService/server",
					},
				],
			},
		]);
		// Both phases carry the names multi opens for the same work, and the
		// caller is handed what the two cost together.
		expect(phaseNamesOf(timing.profileTimed)).toStrictEqual([
			"cleanLeftoverStubs",
			"buildStubs",
		]);
		expect(staged.elapsedMs).toBe(24);
	});

	it("should write a cache stub for each live project and sweep its source leftovers", () => {
		expect.assertions(5);

		const { bar, foo, volume } = stageTwoPackages();

		expect(volume.readFileSync(cacheStub(foo, "src/Server"), "utf8")).toContain(
			'displayName = "client"',
		);
		expect(volume.readFileSync(cacheStub(bar, "src/Server"), "utf8")).toContain(
			'displayName = "server"',
		);
		expect(volume.existsSync(sourceStub(foo, "src/Server"))).toBeFalse();
		expect(volume.existsSync(cacheStub(foo, "src/Dormant"))).toBeFalse();
		expect(volume.existsSync(sourceStub(foo, "src/Dormant"))).toBeTrue();
	});

	it("should yield a bare descriptor for a package no pending entry names", () => {
		expect.assertions(2);

		const context = makeContext("@halcyon/foo", [makeProject("server")]);

		const { fileSystem, volume } = createMemoryFileSystem();

		const { value: descriptors } = stageWorkspaceStubs({
			contexts: [context],
			coverageByPackage: new Map(),
			fileSystem,
			pending: [],
			timing: fakeTimingCollector(12),
		});

		expect(descriptors).toStrictEqual([{ ...context.descriptor, stubMounts: [] }]);
		expect(volume.existsSync(cacheStub(context, "src/Server"))).toBeFalse();
	});

	it("should omit only mounts that contain a user-authored config", () => {
		expect.assertions(3);

		const server = makeProject("server");
		const shared = makeProject("shared", ["src/Shared"]);
		const context = makeContext("@halcyon/foo", [server, shared]);

		const { fileSystem, volume } = createMemoryFileSystem();
		seed(volume, sourceStub(context, "src/Shared"), USER_STUB);

		const { value: descriptors } = stageWorkspaceStubs({
			contexts: [context],
			coverageByPackage: new Map(),
			fileSystem,
			pending: [makePending("@halcyon/foo", server), makePending("@halcyon/foo", shared)],
			timing: fakeTimingCollector(12),
		});

		expect(descriptors[0]!.stubMounts).toStrictEqual([
			{
				absStubPath: cacheStub(context, "src/Server"),
				dataModelPath: "ServerScriptService/server",
			},
		]);
		expect(volume.existsSync(cacheStub(context, "src/Shared"))).toBeFalse();
		expect(volume.readFileSync(sourceStub(context, "src/Shared"), "utf8")).toBe(USER_STUB);
	});

	it("should report every cleaned source stub with package identity", () => {
		expect.assertions(1);

		const project = makeProject("server", ["src/Server", "src/Shared"]);
		const context = makeContext("@halcyon/foo", [project]);

		const { fileSystem, volume } = createMemoryFileSystem();
		seed(volume, sourceStub(context, "src/Server"), GENERATED_STUB);
		seed(volume, sourceStub(context, "src/Shared"), GENERATED_STUB);
		const stderr = vi.spyOn(process.stderr, "write").mockReturnValue(true);

		stageWorkspaceStubs({
			contexts: [context],
			coverageByPackage: new Map(),
			fileSystem,
			pending: [makePending("@halcyon/foo", project)],
			timing: fakeTimingCollector(12),
		});

		expect(stderr).toHaveBeenCalledExactlyOnceWith(
			"jest-roblox: cleaned 2 leftover stub(s) from @halcyon/foo:\n" +
				`  ${sourceStub(context, "src/Server")}\n` +
				`  ${sourceStub(context, "src/Shared")}\n`,
		);
	});

	it("should stay silent when cleanup finds no source stubs", () => {
		expect.assertions(1);

		const project = makeProject("server");
		const context = makeContext("@halcyon/foo", [project]);
		const stderr = vi.spyOn(process.stderr, "write").mockReturnValue(true);

		const { fileSystem } = createMemoryFileSystem();

		stageWorkspaceStubs({
			contexts: [context],
			coverageByPackage: new Map(),
			fileSystem,
			pending: [makePending("@halcyon/foo", project)],
			timing: fakeTimingCollector(12),
		});

		expect(stderr).not.toHaveBeenCalled();
	});
});
