import { Buffer } from "node:buffer";
import fs from "node:fs";
import path from "node:path";

import { stripTsExtension } from "../utils/extensions.ts";
import { ConfigError } from "./errors.ts";
import type { ResolvedProjectConfig } from "./projects.ts";
import type { ProjectTestConfig, ResolvedConfig } from "./schema.ts";
import { PROJECT_TEST_KEYS } from "./schema.ts";

const HEADER = "-- Auto-generated by jest-roblox (do not edit)\n";

export const STUB_FILENAME = "jest.config.luau";

/**
 * Distinguishes own-stubs (safe to delete) from user-authored configs.
 * Reads only the first `HEADER.length` bytes — bounded I/O regardless of
 * file size. Used by workspace pre-flight cleanup and the coverage shadow
 * orphan-sweep to ensure neither ever removes a user's canonical config.
 */
export function isGeneratedStub(filePath: string): boolean {
	if (!fs.existsSync(filePath)) {
		return false;
	}

	try {
		const fd = fs.openSync(filePath, "r");
		try {
			const buffer = Buffer.alloc(HEADER.length);
			const bytesRead = fs.readSync(fd, buffer, 0, HEADER.length, 0);
			return bytesRead === HEADER.length && buffer.toString("utf8") === HEADER;
		} finally {
			fs.closeSync(fd);
		}
	} catch {
		// Defensive catch for unusual FS errors (permission denied,
		// EISDIR, etc.). Caller treats `false` as "not our stub".
		return false;
	}
}

const LEGACY_LUA_FILENAME = "jest.config.lua";

const SKIP_FIELDS: ReadonlySet<string> = new Set(["exclude", "include"]);

export function serializeToLuau(config: ProjectTestConfig): string {
	let output = `${HEADER}return {\n`;

	for (const [key, value] of Object.entries(config)) {
		if (SKIP_FIELDS.has(key)) {
			continue;
		}

		if (value === undefined) {
			continue;
		}

		let serialized: string;
		if (key === "testMatch" && Array.isArray(value)) {
			const stripped = (value as Array<string>).map((pattern) => stripTsExtension(pattern));
			serialized = serializeLuauValue(stripped, "\t");
		} else {
			serialized = serializeLuauValue(value, "\t");
		}

		output += `\t${key} = ${serialized},\n`;
	}

	output += "}\n";
	return output;
}

export function generateProjectConfigs(
	projects: Array<{ config: ProjectTestConfig; outputPath: string }>,
): void {
	for (const project of projects) {
		const directory = path.dirname(project.outputPath);
		if (hasUserAuthoredConfig(directory)) {
			continue;
		}

		const content = serializeToLuau(project.config);
		fs.mkdirSync(directory, { recursive: true });
		fs.writeFileSync(project.outputPath, content, "utf8");

		if (path.basename(project.outputPath) === STUB_FILENAME) {
			removeLegacyGeneratedStub(directory);
		}
	}
}

// All five are valid `ProjectTestConfig` members but the project-level
// values are unwanted in the stub: `outDir`/`root` are reconstructed
// per-mount by `generateProjectStubs`, and `displayName`/`include`/`exclude`
// are overwritten by the spread in `generateProjectStubs` (with
// `include`/`exclude` further dropped by `serializeToLuau`'s `SKIP_FIELDS`).
// Strip them upstream to keep `buildStubConfig`'s output tight.
const STUB_SKIP_KEYS: ReadonlySet<string> = new Set([
	"displayName",
	"exclude",
	"include",
	"outDir",
	"root",
	// Host-only: Type Tests run on the host, never inside the Roblox runtime.
	"typecheck",
]);

/**
 * Refuse to let any downstream write land outside `rootDirectory`. Mount
 * fsPaths originate from the rojo tree and `resolveNestedProjects` can emit
 * values with `..` segments (nested projects relocate paths); combined with
 * `path.resolve` on Windows, a permissive fsPath could send stub writes to
 * `D:\outside\...`. Guard at every write-site.
 */
export function assertMountContained(
	project: ResolvedProjectConfig,
	fsPath: string,
	rootDirectory: string,
): void {
	if (path.isAbsolute(fsPath)) {
		throw new Error(
			`Project "${project.displayName}" mount fsPath must be relative, got: ${fsPath}`,
		);
	}

	const rootResolved = path.resolve(rootDirectory);
	const mountResolved = path.resolve(rootDirectory, fsPath);
	if (mountResolved !== rootResolved && !mountResolved.startsWith(rootResolved + path.sep)) {
		throw new Error(
			`Project "${project.displayName}" mount fsPath escapes root directory: ${fsPath}`,
		);
	}
}

/**
 * True when the mount directory contains a non-marker `jest.config.luau` —
 * i.e. a user-authored config Rojo will sync. Source of truth for whether
 * to skip generating a stub at that mount. Used by `generateProjectStubs`,
 * `cleanLeftoverStubs`'s callers, and the multi-project + workspace runners
 * when deciding stub-write and runtime-injection eligibility.
 */
export function hasUserAuthoredConfig(directoryPath: string): boolean {
	// A `.luau` or legacy `.lua` may be either our generated stub or a
	// user-authored config; only the HEADER prefix distinguishes them.
	// Reuse `isGeneratedStub`'s bounded header-read so this detection
	// check stays cheap (a few bytes) and resilient — unusual FS errors
	// downgrade to "not user-authored" rather than throwing out of a
	// detection helper called from multiple cleanup/build paths.
	const luauPath = path.join(directoryPath, STUB_FILENAME);
	if (fs.existsSync(luauPath) && !isGeneratedStub(luauPath)) {
		return true;
	}

	const luaPath = path.join(directoryPath, LEGACY_LUA_FILENAME);
	return fs.existsSync(luaPath) && !isGeneratedStub(luaPath);
}

/**
 * For a multi-mount project, the stubs-per-mount rule requires that a
 * user-authored config at any tracked FS path must appear at every tracked
 * FS path (or none). Throws `ConfigError` when the project has partial
 * coverage — some mounts have a user config and others don't.
 */
export function assertStubCollisionRule(
	project: ResolvedProjectConfig,
	rootDirectory: string,
): void {
	const withUser: Array<string> = [];
	const withoutUser: Array<string> = [];

	for (const mount of project.rojoMounts) {
		assertMountContained(project, mount.fsPath, rootDirectory);

		const absolute = path.resolve(rootDirectory, mount.fsPath);
		if (hasUserAuthoredConfig(absolute)) {
			withUser.push(mount.fsPath);
		} else {
			withoutUser.push(mount.fsPath);
		}
	}

	if (withUser.length === 0 || withoutUser.length === 0) {
		return;
	}

	const withUserList = withUser.join(", ");
	const withoutUserList = withoutUser.join(", ");
	throw new ConfigError(
		`Project "${project.displayName}": user-authored jest config present at some mounts but not others.\n\n` +
			`With user config: ${withUserList}\n` +
			`Without user config: ${withoutUserList}\n\n` +
			"For multi-mount projects, either every tracked mount must have a user config, or none.",
	);
}

/**
 * Pre-flight cleanup of marker-bearing leftover stubs at known mount paths.
 * Walks O(mounts), no recursive scan. Returns the cleaned paths so callers
 * can surface a `stderr` notice.
 *
 * Containment is enforced at two layers because either alone has a hole:
 * - `assertMountContained` rejects absolute paths and `..`-escapes lexically
 *   (Rojo-derived mounts can carry `..` segments when `resolveNestedProjects`
 *   relocates a path).
 * - `path.relative` against the realpath-resolved root catches symlinked
 *   mount directories pointing outside the package root. Platform-correct —
 *   it honours only the OS's separator, so a POSIX filename literally
 *   containing `\` doesn't pass as if it were a Windows escape.
 */
export function cleanLeftoverStubs(
	projects: Array<ResolvedProjectConfig>,
	rootDirectory: string,
): Array<string> {
	const cleaned: Array<string> = [];
	let realRoot: string | undefined;
	function realRootResolved(): string {
		realRoot ??= fs.realpathSync(path.resolve(rootDirectory));
		return realRoot;
	}

	for (const project of projects) {
		cleaned.push(...cleanLeftoverStubsForProject(project, rootDirectory, realRootResolved));
	}

	return cleaned;
}

export function generateProjectStubs(
	projects: Array<ResolvedProjectConfig>,
	rootDirectory: string,
	outputRoot?: string,
): void {
	const writeRoot = outputRoot ?? rootDirectory;
	const entries: Array<{ config: ProjectTestConfig; outputPath: string }> = [];

	for (const project of projects) {
		assertStubCollisionRule(project, rootDirectory);

		const stubConfig: ProjectTestConfig = {
			...buildStubConfig(project.config),
			displayName: project.displayName,
			include: [],
			testMatch: project.testMatch,
		};

		entries.push(...buildStubEntriesForProject(project, stubConfig, rootDirectory, writeRoot));
	}

	generateProjectConfigs(entries);
}

export function syncStubsToShadowDirectory(
	projects: Array<ResolvedProjectConfig>,
	rootDirectory: string,
	shadowDirectory: string,
): boolean {
	let changed = false;
	const expectedPaths = new Set<string>();

	for (const project of projects) {
		for (const mount of project.rojoMounts) {
			const result = syncMountStub(project, mount.fsPath, rootDirectory, shadowDirectory);
			if (result.targetPath !== undefined) {
				expectedPaths.add(result.targetPath);
			}

			changed ||= result.changed;
		}
	}

	for (const existing of findShadowStubs(shadowDirectory)) {
		if (expectedPaths.has(existing)) {
			continue;
		}

		// `prepareCoverage` mirrors the source tree into the shadow before
		// this hook runs, so a user's authored `jest.config.luau` (e.g.
		// compiled from `src/shared/jest.config.ts`) may land here. The
		// orphan sweep is only allowed to delete generated stubs we own —
		// anything bearing the marker. User configs must survive into the
		// coverage place.
		if (!isGeneratedStub(existing)) {
			continue;
		}

		fs.unlinkSync(existing);
		removeEmptyParents(path.dirname(existing), shadowDirectory);
		changed = true;
	}

	return changed;
}

function cleanLeftoverStubsForProject(
	project: ResolvedProjectConfig,
	rootDirectory: string,
	realRootResolved: () => string,
): Array<string> {
	const cleaned: Array<string> = [];
	for (const mount of project.rojoMounts) {
		assertMountContained(project, mount.fsPath, rootDirectory);
		const stubPath = path.resolve(rootDirectory, mount.fsPath, STUB_FILENAME);
		if (!isGeneratedStub(stubPath)) {
			continue;
		}

		const realStubPath = fs.realpathSync(stubPath);
		const root = realRootResolved();
		const relativePath = path.relative(root, realStubPath);
		const inRoot =
			relativePath === "" ||
			(!relativePath.startsWith("..") && !path.isAbsolute(relativePath));
		if (!inRoot) {
			throw new Error(
				`Project "${project.displayName}" mount fsPath resolves outside root via symlink: ${mount.fsPath} → ${realStubPath}`,
			);
		}

		fs.unlinkSync(stubPath);
		cleaned.push(stubPath);
	}

	return cleaned;
}

function buildStubEntriesForProject(
	project: ResolvedProjectConfig,
	stubConfig: ProjectTestConfig,
	rootDirectory: string,
	writeRoot: string,
): Array<{ config: ProjectTestConfig; outputPath: string }> {
	const entries: Array<{ config: ProjectTestConfig; outputPath: string }> = [];
	for (const mount of project.rojoMounts) {
		assertMountContained(project, mount.fsPath, writeRoot);
		// Per-mount FS check — skip generation when a non-marker
		// `jest.config.luau` already exists at the mount on disk.
		// A schema-level "is this a user-authored project" hint is
		// not enough: a TS string-entry whose compile hasn't run
		// yet still needs a generated stub for the mount.
		const sourceMount = path.resolve(rootDirectory, mount.fsPath);
		if (hasUserAuthoredConfig(sourceMount)) {
			continue;
		}

		const outputPath = path.resolve(writeRoot, mount.fsPath, STUB_FILENAME);
		entries.push({ config: stubConfig, outputPath });
	}

	return entries;
}

function buildStubConfig(config: ResolvedConfig): Partial<ProjectTestConfig> {
	const result: Record<string, unknown> = {};
	for (const [key, value] of Object.entries(config)) {
		if (PROJECT_TEST_KEYS.has(key) && !STUB_SKIP_KEYS.has(key) && value !== undefined) {
			result[key] = value;
		}
	}

	return result;
}

function syncMountStub(
	project: ResolvedProjectConfig,
	fsPath: string,
	rootDirectory: string,
	shadowDirectory: string,
): { changed: boolean; targetPath: string | undefined } {
	assertMountContained(project, fsPath, rootDirectory);

	const sourcePath = path.resolve(rootDirectory, fsPath, STUB_FILENAME);
	if (!fs.existsSync(sourcePath)) {
		return { changed: false, targetPath: undefined };
	}

	const targetPath = path.resolve(shadowDirectory, fsPath, STUB_FILENAME);
	const sourceContent = fs.readFileSync(sourcePath);

	if (fs.existsSync(targetPath)) {
		const targetContent = fs.readFileSync(targetPath);
		if (Buffer.compare(sourceContent, targetContent) === 0) {
			return { changed: false, targetPath };
		}
	}

	fs.mkdirSync(path.dirname(targetPath), { recursive: true });
	fs.copyFileSync(sourcePath, targetPath);
	return { changed: true, targetPath };
}

function findShadowStubs(directory: string): Array<string> {
	const results: Array<string> = [];
	if (!fs.existsSync(directory)) {
		return results;
	}

	const entries = fs.readdirSync(directory, { withFileTypes: true });
	for (const entry of entries) {
		const fullPath = path.resolve(directory, entry.name);
		if (entry.isDirectory()) {
			results.push(...findShadowStubs(fullPath));
		} else if (entry.name === STUB_FILENAME || entry.name === LEGACY_LUA_FILENAME) {
			results.push(fullPath);
		}
	}

	return results;
}

function removeEmptyParents(directory: string, stopAt: string): void {
	const resolved = path.resolve(directory);
	const resolvedStop = path.resolve(stopAt);
	if (resolved === resolvedStop || !resolved.startsWith(resolvedStop)) {
		return;
	}

	try {
		const entries = fs.readdirSync(resolved);
		if (entries.length === 0) {
			fs.rmdirSync(resolved);
			removeEmptyParents(path.dirname(resolved), stopAt);
		}
	} catch {
		// Best-effort cleanup
	}
}

// Rojo merges `jest.config.lua` and `jest.config.luau` into the same
// ModuleScript name, so leaving an old generated `.lua` stub next to the
// new `.luau` would cause a name collision after upgrade. Caller guarantees
// (via `hasUserAuthoredConfig`) that any `.lua` present here is our own
// HEADER-prefixed stub, not a user-authored file.
function removeLegacyGeneratedStub(directoryPath: string): void {
	const legacyPath = path.join(directoryPath, LEGACY_LUA_FILENAME);
	if (fs.existsSync(legacyPath)) {
		fs.unlinkSync(legacyPath);
	}
}

function escapeString(value: string): string {
	return value
		.replace(/\\/g, "\\\\")
		.replace(/"/g, '\\"')
		.replace(/\n/g, "\\n")
		.replace(/\r/g, "\\r")
		.replace(/\t/g, "\\t");
}

function serializeLuauValue(value: unknown, indent: string): string {
	if (typeof value === "string") {
		return `"${escapeString(value)}"`;
	}

	if (typeof value === "boolean") {
		return value ? "true" : "false";
	}

	if (typeof value === "number") {
		return String(value);
	}

	if (Array.isArray(value)) {
		const items = value.map((item: unknown) => serializeLuauValue(item, indent));
		return `{ ${items.join(", ")} }`;
	}

	if (typeof value === "object" && value !== null) {
		const nextIndent = `${indent}\t`;
		const entries = Object.entries(value)
			.filter(([, value_]) => value_ !== undefined)
			.map(([key, value_]) => `${key} = ${serializeLuauValue(value_, nextIndent)}`);
		return `{ ${entries.join(", ")} }`;
	}

	return String(value);
}
