import { Buffer } from "node:buffer";
import fs from "node:fs";
import path from "node:path";

import { stripTsExtension } from "../utils/extensions.ts";
import type { ResolvedProjectConfig } from "./projects.ts";
import type { ProjectTestConfig } from "./schema.ts";

const HEADER = "-- Auto-generated by jest-roblox (do not edit)\n";

const SKIP_FIELDS: ReadonlySet<string> = new Set(["exclude", "include"]);

export function serializeToLuau(config: ProjectTestConfig): string {
	let output = `${HEADER}return {\n`;

	for (const [key, value] of Object.entries(config)) {
		if (SKIP_FIELDS.has(key)) {
			continue;
		}

		if (value === undefined) {
			continue;
		}

		let serialized: string;
		if (key === "testMatch" && Array.isArray(value)) {
			const stripped = (value as Array<string>).map((pattern) => stripTsExtension(pattern));
			serialized = serializeLuauValue(stripped, "\t");
		} else {
			serialized = serializeLuauValue(value, "\t");
		}

		output += `\t${key} = ${serialized},\n`;
	}

	output += "}\n";
	return output;
}

export function generateProjectConfigs(
	projects: Array<{ config: ProjectTestConfig; outputPath: string }>,
): void {
	for (const project of projects) {
		const luauConfigPath = project.outputPath.replace(/\.lua$/, ".luau");
		if (fs.existsSync(luauConfigPath)) {
			continue;
		}

		const content = serializeToLuau(project.config);
		const directory = path.dirname(project.outputPath);
		fs.mkdirSync(directory, { recursive: true });
		fs.writeFileSync(project.outputPath, content, "utf8");
	}
}

export function syncStubsToShadowDirectory(
	projects: Array<ResolvedProjectConfig>,
	rootDirectory: string,
	shadowDirectory: string,
): boolean {
	let changed = false;
	const expectedPaths = new Set<string>();

	for (const project of projects) {
		if (project.outDir === undefined) {
			continue;
		}

		if (path.isAbsolute(project.outDir)) {
			throw new Error(
				`Project "${project.displayName}" outDir must be a relative path, got: ${project.outDir}`,
			);
		}

		const stubName = "jest.config.lua";
		const sourcePath = path.resolve(rootDirectory, project.outDir, stubName);
		if (!fs.existsSync(sourcePath)) {
			continue;
		}

		const targetPath = path.resolve(shadowDirectory, project.outDir, stubName);
		expectedPaths.add(targetPath);
		const sourceContent = fs.readFileSync(sourcePath);

		if (fs.existsSync(targetPath)) {
			const targetContent = fs.readFileSync(targetPath);
			if (Buffer.compare(sourceContent, targetContent) === 0) {
				continue;
			}
		}

		fs.mkdirSync(path.dirname(targetPath), { recursive: true });
		fs.copyFileSync(sourcePath, targetPath);
		changed = true;
	}

	for (const existing of findShadowStubs(shadowDirectory)) {
		if (!expectedPaths.has(existing)) {
			fs.unlinkSync(existing);
			removeEmptyParents(path.dirname(existing), shadowDirectory);
			changed = true;
		}
	}

	return changed;
}

function escapeString(value: string): string {
	return value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

function serializeLuauValue(value: unknown, indent: string): string {
	if (typeof value === "string") {
		return `"${escapeString(value)}"`;
	}

	if (typeof value === "boolean") {
		return value ? "true" : "false";
	}

	if (typeof value === "number") {
		return String(value);
	}

	if (Array.isArray(value)) {
		const items = value.map((item: unknown) => serializeLuauValue(item, indent));
		return `{ ${items.join(", ")} }`;
	}

	if (typeof value === "object" && value !== null) {
		const nextIndent = `${indent}\t`;
		const entries = Object.entries(value)
			.filter(([, value_]) => value_ !== undefined)
			.map(([key, value_]) => `${key} = ${serializeLuauValue(value_, nextIndent)}`);
		return `{ ${entries.join(", ")} }`;
	}

	return String(value);
}

function removeEmptyParents(directory: string, stopAt: string): void {
	const resolved = path.resolve(directory);
	const resolvedStop = path.resolve(stopAt);
	if (resolved === resolvedStop || !resolved.startsWith(resolvedStop)) {
		return;
	}

	try {
		const entries = fs.readdirSync(resolved);
		if (entries.length === 0) {
			fs.rmdirSync(resolved);
			removeEmptyParents(path.dirname(resolved), stopAt);
		}
	} catch {
		// Best-effort cleanup
	}
}

function findShadowStubs(directory: string): Array<string> {
	const results: Array<string> = [];
	if (!fs.existsSync(directory)) {
		return results;
	}

	const entries = fs.readdirSync(directory, { withFileTypes: true });
	for (const entry of entries) {
		const fullPath = path.resolve(directory, entry.name);
		if (entry.isDirectory()) {
			results.push(...findShadowStubs(fullPath));
		} else if (entry.name === "jest.config.lua") {
			results.push(fullPath);
		}
	}

	return results;
}
