import { fromAny } from "@total-typescript/shoehorn";

import * as path from "node:path";
import { assert, describe, expect, it, vi } from "vitest";

import { createMemoryFileSystem } from "../../test/mocks/memory-file-system.ts";
import type { ShadowLayout } from "../coverage-pipeline/spine.ts";
import { ConfigError } from "./errors.ts";
import type { ResolvedProjectConfig } from "./projects.ts";
import type { ProjectTestConfig, ResolvedConfig } from "./schema.ts";
import { DEFAULT_CONFIG } from "./schema.ts";
import {
	assertStubCollisionRule,
	cleanLeftoverStubs,
	generateProjectConfigs,
	generateProjectStubs,
	isGeneratedStub,
	serializeToLuau,
	syncStubsToShadowDirectory,
} from "./stubs.ts";

function makeResolvedProject(
	overrides: Partial<ResolvedProjectConfig> = {},
): ResolvedProjectConfig {
	const config: ResolvedConfig = {
		...DEFAULT_CONFIG,
		rootDir: "/root",
	};
	return {
		config,
		displayName: "client",
		exclude: [],
		include: ["src/client/**/*.spec.ts"],
		outDir: "out/client",
		projects: ["ReplicatedStorage/client"],
		rojoMounts: [{ dataModelPath: "ReplicatedStorage/client", fsPath: "out/client" }],
		testMatch: ["**/*.spec"],
		...overrides,
	};
}

function minimalConfig(overrides: Partial<ProjectTestConfig> = {}): ProjectTestConfig {
	return {
		displayName: "test",
		include: ["src/**"],
		...overrides,
	};
}

describe(serializeToLuau, () => {
	it("should serialize the complete stub contract exactly", () => {
		expect.assertions(1);

		expect(
			serializeToLuau({
				clearMocks: true,
				displayName: { name: "client", color: "blue" },
				exclude: ["ignored/**"],
				include: ["src/**"],
				restoreMocks: false,
				setupFiles: ["ReplicatedStorage/setup"],
				slowTestThreshold: 3,
				testEnvironment: "custom",
				testMatch: ["**/*.spec.ts", "**/*.test.tsx"],
				testTimeout: 5000,
			}),
		).toBe(
			[
				"-- Auto-generated by jest-roblox (do not edit)",
				"return {",
				"\tclearMocks = true,",
				'\tdisplayName = { name = "client", color = "blue" },',
				"\trestoreMocks = false,",
				'\tsetupFiles = { "ReplicatedStorage/setup" },',
				"\tslowTestThreshold = 3,",
				'\ttestEnvironment = "custom",',
				'\ttestMatch = { "**/*.spec", "**/*.test" },',
				"\ttestTimeout = 5000,",
				"}",
				"",
			].join("\n"),
		);
	});

	it("should serialize displayName string", () => {
		expect.assertions(1);

		const result = serializeToLuau(minimalConfig({ displayName: "client" }));

		expect(result).toContain('\tdisplayName = "client",');
	});

	it("should serialize displayName object with name and color", () => {
		expect.assertions(1);

		const result = serializeToLuau(
			minimalConfig({
				displayName: { name: "client", color: "blue" },
			}),
		);

		expect(result).toContain('\tdisplayName = { name = "client", color = "blue" },');
	});

	it("should serialize testMatch array with stripped extensions", () => {
		expect.assertions(1);

		const result = serializeToLuau(
			minimalConfig({
				testMatch: ["**/*.spec.ts", "**/*.test.tsx", "**/*.spec.luau"],
			}),
		);

		expect(result).toContain('\ttestMatch = { "**/*.spec", "**/*.test", "**/*.spec" },');
	});

	it("should preserve TypeScript extensions outside testMatch", () => {
		expect.assertions(1);

		const result = serializeToLuau(
			minimalConfig({ setupFiles: ["ReplicatedStorage/setup.ts"] }),
		);

		expect(result).toContain('\tsetupFiles = { "ReplicatedStorage/setup.ts" },');
	});

	it("should serialize boolean fields", () => {
		expect.assertions(2);

		const result = serializeToLuau(minimalConfig({ clearMocks: true, restoreMocks: false }));

		expect(result).toContain("\tclearMocks = true,");
		expect(result).toContain("\trestoreMocks = false,");
	});

	it("should serialize number fields", () => {
		expect.assertions(1);

		const result = serializeToLuau(minimalConfig({ slowTestThreshold: 5 }));

		expect(result).toContain("\tslowTestThreshold = 5,");
	});

	it("should serialize snapshotFormat nested object", () => {
		expect.assertions(1);

		const result = serializeToLuau(
			minimalConfig({
				snapshotFormat: { indent: 4, printBasicPrototype: false },
			}),
		);

		expect(result).toContain("\tsnapshotFormat = { indent = 4, printBasicPrototype = false },");
	});

	it("should omit undefined nested properties", () => {
		expect.assertions(1);

		const result = serializeToLuau(
			minimalConfig({
				snapshotFormat: fromAny({ indent: 4, printBasicPrototype: undefined }),
			}),
		);

		expect(result).toContain("\tsnapshotFormat = { indent = 4 },");
	});

	it("should skip include and exclude fields", () => {
		expect.assertions(2);

		const result = serializeToLuau(
			minimalConfig({
				exclude: ["node_modules/**"],
				include: ["src/**"],
			}),
		);

		expect(result).not.toContain("include");
		expect(result).not.toContain("exclude");
	});

	it("should skip undefined values", () => {
		expect.assertions(1);

		const result = serializeToLuau({ ...minimalConfig(), setupFiles: undefined });

		expect(result).not.toContain("setupFiles");
	});

	it("should escape quotes in string values", () => {
		expect.assertions(1);

		const result = serializeToLuau(minimalConfig({ testEnvironment: 'env\\with"quotes' }));

		expect(result).toContain('\ttestEnvironment = "env\\\\with\\"quotes",');
	});

	it("should escape newlines, carriage returns, and tabs in string values", () => {
		expect.assertions(1);

		const result = serializeToLuau(
			minimalConfig({ testEnvironment: "line1\nline2\rline3\twith-tab" }),
		);

		expect(result).toContain('\ttestEnvironment = "line1\\nline2\\rline3\\twith-tab",');
	});

	it("should add auto-generated header comment", () => {
		expect.assertions(1);

		const result = serializeToLuau(minimalConfig());

		expect(result).toStartWith("-- Auto-generated by jest-roblox (do not edit)\n");
	});

	it("should serialize all project config fields", () => {
		expect.assertions(4);

		const config: ProjectTestConfig = {
			clearMocks: true,
			displayName: "client",
			include: ["src/client/**/*.spec.ts"],
			setupFiles: ["ReplicatedStorage/setup"],
			testMatch: ["**/*.spec.ts"],
			testTimeout: 5000,
		};
		const result = serializeToLuau(config);

		expect(result).toContain("clearMocks = true");
		expect(result).toContain("testTimeout = 5000");
		expect(result).toContain('setupFiles = { "ReplicatedStorage/setup" }');
		expect(result).toContain("testMatch");
	});

	it("should serialize null values via String fallback", () => {
		expect.assertions(1);

		// serializeLuauValue falls through to String(null) → "null" for
		// unrecognized types. This is intentional fallback behavior.
		const config: ProjectTestConfig = fromAny({
			displayName: "test",
			include: ["src/**"],
			testTimeout: null,
		});
		const result = serializeToLuau(config);

		expect(result).toContain("testTimeout = null,");
	});
});

describe(generateProjectConfigs, () => {
	it("should write config file to specified path", () => {
		expect.assertions(1);

		const { fileSystem, volume } = createMemoryFileSystem();

		generateProjectConfigs(
			[
				{
					config: minimalConfig({ displayName: "client" }),
					outputPath: "/out/client.config.luau",
				},
			],
			fileSystem,
		);

		const content = volume.readFileSync("/out/client.config.luau", "utf8");

		expect(content).toContain('\tdisplayName = "client",');
	});

	it("should create parent directories if they don't exist", () => {
		expect.assertions(1);

		const { fileSystem, volume } = createMemoryFileSystem();

		generateProjectConfigs(
			[
				{
					config: minimalConfig(),
					outputPath: "/deep/nested/dir/test.config.luau",
				},
			],
			fileSystem,
		);

		expect(volume.existsSync("/deep/nested/dir/test.config.luau")).toBeTrue();
	});

	it("should skip writing when jest.config.luau already exists at output directory", () => {
		expect.assertions(1);

		const { fileSystem, volume } = createMemoryFileSystem();

		volume.mkdirSync("/out/client", { recursive: true });

		volume.writeFileSync("/out/client/jest.config.luau", "return {}");

		generateProjectConfigs(
			[
				{
					config: minimalConfig({ displayName: "client" }),
					outputPath: "/out/client/jest.config.luau",
				},
			],
			fileSystem,
		);

		expect(volume.readFileSync("/out/client/jest.config.luau", "utf8")).toBe("return {}");
	});

	it("should write config files for multiple roots", () => {
		expect.assertions(2);

		const { fileSystem, volume } = createMemoryFileSystem();

		generateProjectConfigs(
			[
				{
					config: { displayName: "client", include: [], testMatch: ["**/*.spec"] },
					outputPath: "/out/client/jest.config.luau",
				},
				{
					config: { displayName: "server", include: [], testMatch: ["**/*.spec"] },
					outputPath: "/out/server/jest.config.luau",
				},
			],
			fileSystem,
		);

		expect(volume.existsSync("/out/client/jest.config.luau")).toBeTrue();

		expect(volume.existsSync("/out/server/jest.config.luau")).toBeTrue();
	});

	it("should write multiple project configs", () => {
		expect.assertions(2);

		const { fileSystem, volume } = createMemoryFileSystem();

		generateProjectConfigs(
			[
				{
					config: minimalConfig({ displayName: "client" }),
					outputPath: "/out/client.config.luau",
				},
				{
					config: minimalConfig({ displayName: "server" }),
					outputPath: "/out/server.config.luau",
				},
			],
			fileSystem,
		);

		const client = volume.readFileSync("/out/client.config.luau", "utf8");

		const server = volume.readFileSync("/out/server.config.luau", "utf8");

		expect(client).toContain('\tdisplayName = "client",');
		expect(server).toContain('\tdisplayName = "server",');
	});
});

/** A shadow whose mirror is where every mount is read from — no demote. */
function shadowAt(root: string): ShadowLayout {
	return { mountedDirectory: (relative) => path.posix.join(root, relative), root };
}

describe(syncStubsToShadowDirectory, () => {
	it("should copy stub files from original dirs to shadow dir", () => {
		expect.assertions(1);

		const { fileSystem, volume } = createMemoryFileSystem();

		volume.mkdirSync("/root/out/client", { recursive: true });

		volume.writeFileSync("/root/out/client/jest.config.luau", "-- stub");

		const projects = [makeResolvedProject({ outDir: "out/client" })];

		syncStubsToShadowDirectory(projects, "/root", shadowAt("/shadow"), fileSystem);

		expect(volume.readFileSync("/shadow/out/client/jest.config.luau", "utf8")).toBe("-- stub");
	});

	it("should return true when stub is new", () => {
		expect.assertions(1);

		const { fileSystem, volume } = createMemoryFileSystem();

		volume.mkdirSync("/root/out/client", { recursive: true });

		volume.writeFileSync("/root/out/client/jest.config.luau", "-- stub");

		const projects = [makeResolvedProject({ outDir: "out/client" })];

		const hasChanged = syncStubsToShadowDirectory(
			projects,
			"/root",
			shadowAt("/shadow"),
			fileSystem,
		);

		expect(hasChanged).toBeTrue();
	});

	it("should return true when stub content changed", () => {
		expect.assertions(1);

		const { fileSystem, volume } = createMemoryFileSystem();

		volume.mkdirSync("/root/out/client", { recursive: true });

		volume.writeFileSync("/root/out/client/jest.config.luau", "-- updated");
		volume.mkdirSync("/shadow/out/client", { recursive: true });
		volume.writeFileSync("/shadow/out/client/jest.config.luau", "-- old");

		const projects = [makeResolvedProject({ outDir: "out/client" })];

		const hasChanged = syncStubsToShadowDirectory(
			projects,
			"/root",
			shadowAt("/shadow"),
			fileSystem,
		);

		expect(hasChanged).toBeTrue();
	});

	it("should return false when stub content identical", () => {
		expect.assertions(1);

		const { fileSystem, volume } = createMemoryFileSystem();

		volume.mkdirSync("/root/out/client", { recursive: true });

		volume.writeFileSync("/root/out/client/jest.config.luau", "-- same");
		volume.mkdirSync("/shadow/out/client", { recursive: true });
		volume.writeFileSync("/shadow/out/client/jest.config.luau", "-- same");

		const projects = [makeResolvedProject({ outDir: "out/client" })];

		const hasChanged = syncStubsToShadowDirectory(
			projects,
			"/root",
			shadowAt("/shadow"),
			fileSystem,
		);

		expect(hasChanged).toBeFalse();
	});

	it("should skip projects with empty rojoMounts", () => {
		expect.assertions(1);

		const { fileSystem } = createMemoryFileSystem();

		const projects = [makeResolvedProject({ outDir: undefined, rojoMounts: [] })];

		const hasChanged = syncStubsToShadowDirectory(
			projects,
			"/root",
			shadowAt("/shadow"),
			fileSystem,
		);

		expect(hasChanged).toBeFalse();
	});

	it("should create directories in shadow dir as needed", () => {
		expect.assertions(1);

		const { fileSystem, volume } = createMemoryFileSystem();

		volume.mkdirSync("/root/out/deep/nested", { recursive: true });

		volume.writeFileSync("/root/out/deep/nested/jest.config.luau", "-- stub");

		const projects = [
			makeResolvedProject({
				outDir: "out/deep/nested",
				rojoMounts: [
					{ dataModelPath: "ReplicatedStorage/deep", fsPath: "out/deep/nested" },
				],
			}),
		];

		syncStubsToShadowDirectory(projects, "/root", shadowAt("/shadow"), fileSystem);

		expect(volume.existsSync("/shadow/out/deep/nested/jest.config.luau")).toBeTrue();
	});

	it("should delete orphaned shadow stubs not in current projects and return true", () => {
		expect.assertions(2);

		const { fileSystem, volume } = createMemoryFileSystem();

		// Orphaned stub in shadow dir (no matching project)
		volume.mkdirSync("/shadow/out/removed", { recursive: true });

		volume.writeFileSync(
			"/shadow/out/removed/jest.config.luau",
			"-- Auto-generated by jest-roblox (do not edit)\n",
		);

		const projects: Array<ResolvedProjectConfig> = [];

		const hasChanged = syncStubsToShadowDirectory(
			projects,
			"/root",
			shadowAt("/shadow"),
			fileSystem,
		);

		expect(hasChanged).toBeTrue();
		expect(volume.existsSync("/shadow/out/removed/jest.config.luau")).toBeFalse();
	});

	it("should throw when mount fsPath is an absolute path", () => {
		expect.assertions(1);

		const { fileSystem } = createMemoryFileSystem();

		const projects = [
			makeResolvedProject({
				rojoMounts: [{ dataModelPath: "ReplicatedStorage/evil", fsPath: "/tmp/evil" }],
			}),
		];

		expect(() => {
			return syncStubsToShadowDirectory(projects, "/root", shadowAt("/shadow"), fileSystem);
		}).toThrow("mount fsPath must be relative");
	});

	it("should throw when mount fsPath escapes rootDirectory via parent segments", () => {
		expect.assertions(1);

		const { fileSystem } = createMemoryFileSystem();

		const projects = [
			makeResolvedProject({
				rojoMounts: [{ dataModelPath: "ReplicatedStorage/outside", fsPath: "../outside" }],
			}),
		];

		expect(() => {
			return syncStubsToShadowDirectory(projects, "/root", shadowAt("/shadow"), fileSystem);
		}).toThrow("mount fsPath escapes root directory");
	});

	it("should clean up empty parent directories after orphan removal", () => {
		expect.assertions(2);

		const { fileSystem, volume } = createMemoryFileSystem();

		volume.mkdirSync("/shadow/out/removed/deep", { recursive: true });

		volume.writeFileSync(
			"/shadow/out/removed/deep/jest.config.luau",
			"-- Auto-generated by jest-roblox (do not edit)\n",
		);

		const projects: Array<ResolvedProjectConfig> = [];

		syncStubsToShadowDirectory(projects, "/root", shadowAt("/shadow"), fileSystem);

		expect(volume.existsSync("/shadow/out/removed/deep")).toBeFalse();
		expect(volume.existsSync("/shadow/out/removed")).toBeFalse();
	});

	it("should return false when no orphans and no changes", () => {
		expect.assertions(1);

		const { fileSystem } = createMemoryFileSystem();

		// No stubs anywhere, no mounts tracked
		const projects = [makeResolvedProject({ outDir: undefined, rojoMounts: [] })];

		const hasChanged = syncStubsToShadowDirectory(
			projects,
			"/root",
			shadowAt("/shadow"),
			fileSystem,
		);

		expect(hasChanged).toBeFalse();
	});

	it("should not remove parent when it still contains other files", () => {
		expect.assertions(2);

		const { fileSystem, volume } = createMemoryFileSystem();

		volume.mkdirSync("/shadow/out/mixed", { recursive: true });

		volume.writeFileSync(
			"/shadow/out/mixed/jest.config.luau",
			"-- Auto-generated by jest-roblox (do not edit)\n",
		);
		volume.writeFileSync("/shadow/out/mixed/other-file.txt", "keep me");

		const projects: Array<ResolvedProjectConfig> = [];

		syncStubsToShadowDirectory(projects, "/root", shadowAt("/shadow"), fileSystem);

		expect(volume.existsSync("/shadow/out/mixed/jest.config.luau")).toBeFalse();
		expect(volume.existsSync("/shadow/out/mixed/other-file.txt")).toBeTrue();
	});

	it("should ignore non-config files in shadow directory", () => {
		expect.assertions(1);

		const { fileSystem, volume } = createMemoryFileSystem();

		volume.mkdirSync("/shadow/out/project", { recursive: true });

		volume.writeFileSync("/shadow/out/project/not-a-config.lua", "-- not a config");

		const projects: Array<ResolvedProjectConfig> = [];

		const hasChanged = syncStubsToShadowDirectory(
			projects,
			"/root",
			shadowAt("/shadow"),
			fileSystem,
		);

		expect(hasChanged).toBeFalse();
	});

	it("should delete both generated config extensions without sweeping marker-bearing neighbors", () => {
		expect.assertions(5);

		const { fileSystem, volume } = createMemoryFileSystem();

		const marker = "-- Auto-generated by jest-roblox (do not edit)\n";
		volume.fromJSON({
			"/shadow/generated/jest.config.lua": marker,
			"/shadow/generated/jest.config.luau": marker,
			"/shadow/generated/not-a-config.lua": marker,
			"/shadow/user/jest.config.luau": "return {}\n",
		});

		const hasChanged = syncStubsToShadowDirectory([], "/root", shadowAt("/shadow"), fileSystem);

		expect(hasChanged).toBeTrue();

		expect(volume.existsSync("/shadow/generated/jest.config.lua")).toBeFalse();
		expect(volume.existsSync("/shadow/generated/jest.config.luau")).toBeFalse();
		expect(volume.existsSync("/shadow/generated/not-a-config.lua")).toBeTrue();
		expect(volume.existsSync("/shadow/user/jest.config.luau")).toBeTrue();
	});

	it("should skip project when source stub does not exist", () => {
		expect.assertions(1);

		const { fileSystem, volume } = createMemoryFileSystem();

		// outDir exists but jest.config.luau does not
		volume.mkdirSync("/root/out/client", { recursive: true });

		const projects = [makeResolvedProject({ outDir: "out/client" })];

		const hasChanged = syncStubsToShadowDirectory(
			projects,
			"/root",
			shadowAt("/shadow"),
			fileSystem,
		);

		expect(hasChanged).toBeFalse();
	});

	it("should copy stubs from every mount of a multi-mount project", () => {
		expect.assertions(3);

		const { fileSystem, volume } = createMemoryFileSystem();

		volume.mkdirSync("/root/src/Client", { recursive: true });

		volume.mkdirSync("/root/src/Server", { recursive: true });
		volume.mkdirSync("/root/src/Shared", { recursive: true });
		volume.writeFileSync("/root/src/Client/jest.config.luau", "-- stub");
		volume.writeFileSync("/root/src/Server/jest.config.luau", "-- stub");
		volume.writeFileSync("/root/src/Shared/jest.config.luau", "-- stub");

		const projects = [
			makeResolvedProject({
				outDir: undefined,
				rojoMounts: [
					{ dataModelPath: "ReplicatedStorage/Client", fsPath: "src/Client" },
					{ dataModelPath: "ServerScriptService/Server", fsPath: "src/Server" },
					{ dataModelPath: "ReplicatedStorage/Shared", fsPath: "src/Shared" },
				],
			}),
		];

		syncStubsToShadowDirectory(projects, "/root", shadowAt("/shadow"), fileSystem);

		expect(volume.existsSync("/shadow/src/Client/jest.config.luau")).toBeTrue();
		expect(volume.existsSync("/shadow/src/Server/jest.config.luau")).toBeTrue();
		expect(volume.existsSync("/shadow/src/Shared/jest.config.luau")).toBeTrue();
	});

	it("should remove shadow stub when its mount is dropped between runs", () => {
		expect.assertions(2);

		const { fileSystem, volume } = createMemoryFileSystem();

		volume.mkdirSync("/root/src/Client", { recursive: true });

		volume.writeFileSync("/root/src/Client/jest.config.luau", "-- stub");
		volume.mkdirSync("/shadow/src/Client", { recursive: true });
		volume.writeFileSync("/shadow/src/Client/jest.config.luau", "-- stub");
		// Stale shadow stub for a mount that no longer exists.
		volume.mkdirSync("/shadow/src/Removed", { recursive: true });
		volume.writeFileSync(
			"/shadow/src/Removed/jest.config.luau",
			"-- Auto-generated by jest-roblox (do not edit)\n",
		);

		const projects = [
			makeResolvedProject({
				outDir: undefined,
				rojoMounts: [{ dataModelPath: "ReplicatedStorage/Client", fsPath: "src/Client" }],
			}),
		];

		syncStubsToShadowDirectory(projects, "/root", shadowAt("/shadow"), fileSystem);

		expect(volume.existsSync("/shadow/src/Client/jest.config.luau")).toBeTrue();
		expect(volume.existsSync("/shadow/src/Removed/jest.config.luau")).toBeFalse();
	});
});

describe(assertStubCollisionRule, () => {
	it("should accept when no mount has a user-authored config", () => {
		expect.assertions(1);

		const { fileSystem, volume } = createMemoryFileSystem();

		volume.mkdirSync("/root/src/Client", { recursive: true });

		volume.mkdirSync("/root/src/Server", { recursive: true });

		const project = makeResolvedProject({
			outDir: undefined,
			rojoMounts: [
				{ dataModelPath: "ReplicatedStorage/Client", fsPath: "src/Client" },
				{ dataModelPath: "ServerScriptService/Server", fsPath: "src/Server" },
			],
		});

		expect(() => {
			assertStubCollisionRule(project, "/root", fileSystem);
		}).not.toThrow();
	});

	it("should accept when every mount has a user jest.config.luau", () => {
		expect.assertions(1);

		const { fileSystem, volume } = createMemoryFileSystem();

		volume.mkdirSync("/root/src/Client", { recursive: true });

		volume.mkdirSync("/root/src/Server", { recursive: true });
		volume.writeFileSync("/root/src/Client/jest.config.luau", "return {}");
		volume.writeFileSync("/root/src/Server/jest.config.luau", "return {}");

		const project = makeResolvedProject({
			outDir: undefined,
			rojoMounts: [
				{ dataModelPath: "ReplicatedStorage/Client", fsPath: "src/Client" },
				{ dataModelPath: "ServerScriptService/Server", fsPath: "src/Server" },
			],
		});

		expect(() => {
			assertStubCollisionRule(project, "/root", fileSystem);
		}).not.toThrow();
	});

	it("should accept when every mount has a user jest.config.lua (non-generated)", () => {
		expect.assertions(1);

		const { fileSystem, volume } = createMemoryFileSystem();

		volume.mkdirSync("/root/src/Client", { recursive: true });

		volume.mkdirSync("/root/src/Server", { recursive: true });
		volume.writeFileSync("/root/src/Client/jest.config.lua", "-- user wrote this\nreturn {}");
		volume.writeFileSync("/root/src/Server/jest.config.lua", "-- user wrote this\nreturn {}");

		const project = makeResolvedProject({
			outDir: undefined,
			rojoMounts: [
				{ dataModelPath: "ReplicatedStorage/Client", fsPath: "src/Client" },
				{ dataModelPath: "ServerScriptService/Server", fsPath: "src/Server" },
			],
		});

		expect(() => {
			assertStubCollisionRule(project, "/root", fileSystem);
		}).not.toThrow();
	});

	it("should accept when mixed user extensions cover every mount", () => {
		expect.assertions(1);

		const { fileSystem, volume } = createMemoryFileSystem();

		volume.mkdirSync("/root/src/Client", { recursive: true });

		volume.mkdirSync("/root/src/Server", { recursive: true });
		volume.writeFileSync("/root/src/Client/jest.config.luau", "return {}");
		volume.writeFileSync("/root/src/Server/jest.config.lua", "-- user-authored\nreturn {}");

		const project = makeResolvedProject({
			outDir: undefined,
			rojoMounts: [
				{ dataModelPath: "ReplicatedStorage/Client", fsPath: "src/Client" },
				{ dataModelPath: "ServerScriptService/Server", fsPath: "src/Server" },
			],
		});

		expect(() => {
			assertStubCollisionRule(project, "/root", fileSystem);
		}).not.toThrow();
	});

	it("should throw when only some mounts have a user config", () => {
		expect.assertions(1);

		const { fileSystem, volume } = createMemoryFileSystem();

		volume.mkdirSync("/root/src/Client", { recursive: true });

		volume.mkdirSync("/root/src/Server", { recursive: true });
		volume.writeFileSync("/root/src/Client/jest.config.luau", "return {}");

		const project = makeResolvedProject({
			displayName: "partial",
			outDir: undefined,
			rojoMounts: [
				{ dataModelPath: "ReplicatedStorage/Client", fsPath: "src/Client" },
				{ dataModelPath: "ServerScriptService/Server", fsPath: "src/Server" },
			],
		});

		let caught: unknown;
		try {
			assertStubCollisionRule(project, "/root", fileSystem);
		} catch (err) {
			caught = err;
		}

		assert(caught instanceof ConfigError);

		expect(caught.message).toBe(
			[
				'Project "partial": user-authored jest config present at some mounts but not others.',
				"",
				"With user config: src/Client",
				"Without user config: src/Server",
				"",
				"For multi-mount projects, either every tracked mount must have a user config, or none.",
			].join("\n"),
		);
	});

	it("should ignore our own generated .lua when counting user configs", () => {
		expect.assertions(1);

		const { fileSystem, volume } = createMemoryFileSystem();

		volume.mkdirSync("/root/src/Client", { recursive: true });

		volume.mkdirSync("/root/src/Server", { recursive: true });
		// Our generated stub in one mount should not count as a user config.
		volume.writeFileSync(
			"/root/src/Client/jest.config.lua",
			"-- Auto-generated by jest-roblox (do not edit)\nreturn {}",
		);

		const project = makeResolvedProject({
			outDir: undefined,
			rojoMounts: [
				{ dataModelPath: "ReplicatedStorage/Client", fsPath: "src/Client" },
				{ dataModelPath: "ServerScriptService/Server", fsPath: "src/Server" },
			],
		});

		// Both mounts effectively have no user config, so no throw.
		expect(() => {
			assertStubCollisionRule(project, "/root", fileSystem);
		}).not.toThrow();
	});

	it("should list every mount on each side of a partial user-config collision", () => {
		expect.assertions(1);

		const { fileSystem, volume } = createMemoryFileSystem();

		for (const mount of ["Client", "Shared", "Server", "Storage"]) {
			volume.mkdirSync(`/root/src/${mount}`, { recursive: true });
		}

		volume.writeFileSync("/root/src/Client/jest.config.luau", "return {}");
		volume.writeFileSync("/root/src/Shared/jest.config.luau", "return {}");

		const project = makeResolvedProject({
			displayName: "four-mounts",
			outDir: undefined,
			rojoMounts: [
				{ dataModelPath: "ReplicatedStorage/Client", fsPath: "src/Client" },
				{ dataModelPath: "ReplicatedStorage/Shared", fsPath: "src/Shared" },
				{ dataModelPath: "ServerScriptService/Server", fsPath: "src/Server" },
				{ dataModelPath: "ServerStorage/Storage", fsPath: "src/Storage" },
			],
		});

		expect(() => {
			assertStubCollisionRule(project, "/root", fileSystem);
		}).toThrow(
			[
				'Project "four-mounts": user-authored jest config present at some mounts but not others.',
				"",
				"With user config: src/Client, src/Shared",
				"Without user config: src/Server, src/Storage",
				"",
				"For multi-mount projects, either every tracked mount must have a user config, or none.",
			].join("\n"),
		);
	});
});

describe(generateProjectStubs, () => {
	it("should support a mount at the project root", () => {
		expect.assertions(1);

		const { fileSystem, volume } = createMemoryFileSystem();

		const project = makeResolvedProject({
			rojoMounts: [{ dataModelPath: "ReplicatedStorage", fsPath: "." }],
		});

		generateProjectStubs([project], "/root", "/cache/workspace", fileSystem);

		expect(volume.existsSync("/cache/workspace/jest.config.luau")).toBeTrue();
	});

	it("should reject a mount in a sibling directory sharing the root prefix", () => {
		expect.assertions(1);

		const { fileSystem } = createMemoryFileSystem();

		const project = makeResolvedProject({
			rojoMounts: [{ dataModelPath: "ReplicatedStorage", fsPath: "../root-backup" }],
		});

		expect(() => {
			generateProjectStubs([project], "/root", undefined, fileSystem);
		}).toThrow("mount fsPath escapes root directory");
	});

	it("should write stubs to source-tree paths when no outputRoot is given", () => {
		expect.assertions(1);

		const { fileSystem, volume } = createMemoryFileSystem();

		const project = makeResolvedProject({
			displayName: "client",
			rojoMounts: [{ dataModelPath: "ReplicatedStorage/Client", fsPath: "out/Client" }],
		});

		generateProjectStubs([project], "/root", undefined, fileSystem);

		expect(volume.existsSync("/root/out/Client/jest.config.luau")).toBeTrue();
	});

	it("should not emit CLI/runner default fields into the generated stub", () => {
		expect.assertions(3);

		const { fileSystem, volume } = createMemoryFileSystem();

		const project = makeResolvedProject({
			displayName: "client",
			rojoMounts: [{ dataModelPath: "ReplicatedStorage/Client", fsPath: "out/Client" }],
		});

		generateProjectStubs([project], "/root", undefined, fileSystem);

		const content = volume.readFileSync("/root/out/Client/jest.config.luau", "utf8");

		expect(content).not.toContain("silent =");

		expect(content).not.toContain("verbose =");
		expect(content).not.toContain("passWithNoTests =");
	});

	it("should not emit root CLI/runner keys when explicitly set", () => {
		expect.assertions(4);

		const { fileSystem, volume } = createMemoryFileSystem();

		const config: ResolvedConfig = {
			...DEFAULT_CONFIG,
			gameOutput: "out.json",
			outputFile: "results.json",
			port: 4242,
			rootDir: "/root",
		};
		const project = makeResolvedProject({
			config,
			rojoMounts: [{ dataModelPath: "ReplicatedStorage/Client", fsPath: "out/Client" }],
		});

		generateProjectStubs([project], "/root", undefined, fileSystem);

		const content = volume.readFileSync("/root/out/Client/jest.config.luau", "utf8");

		expect(content).not.toContain("outputFile =");

		expect(content).not.toContain("gameOutput =");
		expect(content).not.toContain("port =");
		expect(content).not.toContain("rojoProject =");
	});

	it("should not emit global-only test keys when set", () => {
		expect.assertions(3);

		const { fileSystem, volume } = createMemoryFileSystem();

		const config: ResolvedConfig = {
			...DEFAULT_CONFIG,
			bail: true,
			rootDir: "/root",
			testNamePattern: "foo",
			updateSnapshot: true,
		};
		const project = makeResolvedProject({
			config,
			rojoMounts: [{ dataModelPath: "ReplicatedStorage/Client", fsPath: "out/Client" }],
		});

		generateProjectStubs([project], "/root", undefined, fileSystem);

		const content = volume.readFileSync("/root/out/Client/jest.config.luau", "utf8");

		expect(content).not.toContain("bail =");

		expect(content).not.toContain("testNamePattern =");
		expect(content).not.toContain("updateSnapshot =");
	});

	it("should not emit mount or host-only project values", () => {
		expect.assertions(3);

		const { fileSystem, volume } = createMemoryFileSystem();

		const config: ResolvedConfig = fromAny({
			...DEFAULT_CONFIG,
			outDir: "wrong-out-dir",
			root: "wrong-runtime-root",
			rootDir: "/root",
			typecheck: { enabled: true },
		});

		const project = makeResolvedProject({
			config,
			rojoMounts: [{ dataModelPath: "ReplicatedStorage/Client", fsPath: "out/Client" }],
		});

		generateProjectStubs([project], "/root", undefined, fileSystem);

		const content = volume.readFileSync("/root/out/Client/jest.config.luau", "utf8");

		expect(content).not.toContain("wrong-out-dir");
		expect(content).not.toContain("wrong-runtime-root");
		expect(content).not.toContain("typecheck");
	});

	it("should not emit projectTimeout, which Jest does not know", () => {
		expect.assertions(1);

		const { fileSystem, volume } = createMemoryFileSystem();

		const config: ResolvedConfig = {
			...DEFAULT_CONFIG,
			projectTimeout: 30_000,
			rootDir: "/root",
		};
		const project = makeResolvedProject({
			config,
			rojoMounts: [{ dataModelPath: "ReplicatedStorage/Client", fsPath: "out/Client" }],
		});

		generateProjectStubs([project], "/root", undefined, fileSystem);

		const content = volume.readFileSync("/root/out/Client/jest.config.luau", "utf8");

		expect(content).not.toContain("projectTimeout");
	});

	it("should emit shared jest-passthrough keys when set", () => {
		expect.assertions(3);

		const { fileSystem, volume } = createMemoryFileSystem();

		const config: ResolvedConfig = {
			...DEFAULT_CONFIG,
			clearMocks: true,
			rootDir: "/root",
			setupFiles: ["ReplicatedStorage/setup"],
			testTimeout: 9000,
		};
		const project = makeResolvedProject({
			config,
			rojoMounts: [{ dataModelPath: "ReplicatedStorage/Client", fsPath: "out/Client" }],
		});

		generateProjectStubs([project], "/root", undefined, fileSystem);

		const content = volume.readFileSync("/root/out/Client/jest.config.luau", "utf8");

		expect(content).toContain("clearMocks = true");

		expect(content).toContain('setupFiles = { "ReplicatedStorage/setup" }');
		expect(content).toContain("testTimeout = 9000");
	});

	it("should route stubs to outputRoot when provided", () => {
		expect.assertions(2);

		const { fileSystem, volume } = createMemoryFileSystem();

		const project = makeResolvedProject({
			displayName: "client",
			rojoMounts: [{ dataModelPath: "ReplicatedStorage/Client", fsPath: "out/Client" }],
		});

		generateProjectStubs([project], "/root", "/cache/.jest-roblox/workspace/pkg", fileSystem);

		expect(
			volume.existsSync("/cache/.jest-roblox/workspace/pkg/out/Client/jest.config.luau"),
		).toBeTrue();

		// Source tree untouched.
		expect(volume.existsSync("/root/out/Client/jest.config.luau")).toBeFalse();
	});

	it("should reject absolute mount fsPath when outputRoot is provided", () => {
		expect.assertions(1);

		const { fileSystem } = createMemoryFileSystem();

		const project = makeResolvedProject({
			displayName: "evil",
			rojoMounts: [{ dataModelPath: "ReplicatedStorage/Evil", fsPath: "/abs/path" }],
		});

		expect(() => {
			generateProjectStubs(
				[project],
				"/root",
				"/cache/.jest-roblox/workspace/pkg",
				fileSystem,
			);
		}).toThrow("mount fsPath must be relative");
	});

	it("should still detect partial user-authored configs in source tree when writing to outputRoot", () => {
		expect.assertions(2);

		const { fileSystem, volume } = createMemoryFileSystem();

		// User config in source tree at one mount but not the other → partial
		// coverage.
		volume.mkdirSync("/root/out/Client", { recursive: true });

		volume.writeFileSync("/root/out/Client/jest.config.luau", "return {}");
		volume.mkdirSync("/root/out/Server", { recursive: true });

		const project = makeResolvedProject({
			displayName: "partial",
			rojoMounts: [
				{ dataModelPath: "ReplicatedStorage/Client", fsPath: "out/Client" },
				{ dataModelPath: "ServerScriptService/Server", fsPath: "out/Server" },
			],
		});

		expect(() => {
			generateProjectStubs(
				[project],
				"/root",
				"/cache/.jest-roblox/workspace/pkg",
				fileSystem,
			);
		}).toThrow(ConfigError);
		// No stub written to cache because the guard fires before any write.
		expect(
			volume.existsSync("/cache/.jest-roblox/workspace/pkg/out/Server/jest.config.luau"),
		).toBeFalse();
	});
});

describe("generateProjectConfigs with multi-mount projects", () => {
	it("should write identical stubs at every mount's outputPath", () => {
		expect.assertions(3);

		const { fileSystem, volume } = createMemoryFileSystem();

		const stubConfig: ProjectTestConfig = {
			displayName: "friends",
			include: [],
			testMatch: ["**/*.spec"],
		};

		generateProjectConfigs(
			[
				{ config: stubConfig, outputPath: "/root/src/Client/jest.config.luau" },
				{ config: stubConfig, outputPath: "/root/src/Server/jest.config.luau" },
				{ config: stubConfig, outputPath: "/root/src/Shared/jest.config.luau" },
			],
			fileSystem,
		);

		const clientContent = volume.readFileSync("/root/src/Client/jest.config.luau", "utf8");

		const serverContent = volume.readFileSync("/root/src/Server/jest.config.luau", "utf8");
		const sharedContent = volume.readFileSync("/root/src/Shared/jest.config.luau", "utf8");

		expect(clientContent).toBe(serverContent);
		expect(serverContent).toBe(sharedContent);
		expect(clientContent).toContain('\tdisplayName = "friends",');
	});

	it("should skip writing when user's jest.config.lua exists at target", () => {
		expect.assertions(1);

		const { fileSystem, volume } = createMemoryFileSystem();

		volume.mkdirSync("/root/src/Client", { recursive: true });

		volume.writeFileSync("/root/src/Client/jest.config.lua", "-- user-authored\nreturn {}");

		generateProjectConfigs(
			[
				{
					config: { displayName: "friends", include: [], testMatch: ["**/*.spec"] },
					outputPath: "/root/src/Client/jest.config.lua",
				},
			],
			fileSystem,
		);

		// User's file preserved, not overwritten.
		expect(volume.readFileSync("/root/src/Client/jest.config.lua", "utf8")).toBe(
			"-- user-authored\nreturn {}",
		);
	});

	it("should overwrite our own previously-generated stub on re-gen", () => {
		expect.assertions(1);

		const { fileSystem, volume } = createMemoryFileSystem();

		volume.mkdirSync("/root/src/Client", { recursive: true });

		volume.writeFileSync(
			"/root/src/Client/jest.config.luau",
			"-- Auto-generated by jest-roblox (do not edit)\n-- old content\n",
		);

		generateProjectConfigs(
			[
				{
					config: { displayName: "updated", include: [], testMatch: ["**/*.spec"] },
					outputPath: "/root/src/Client/jest.config.luau",
				},
			],
			fileSystem,
		);

		expect(volume.readFileSync("/root/src/Client/jest.config.luau", "utf8")).toContain(
			'\tdisplayName = "updated",',
		);
	});

	it("should delete a HEADER-prefixed legacy jest.config.lua sibling when writing the .luau stub", () => {
		expect.assertions(2);

		const { fileSystem, volume } = createMemoryFileSystem();

		volume.mkdirSync("/root/src/Client", { recursive: true });

		// Simulate an upgrade: the old run wrote a `.lua` stub; the new run
		// must delete it so Rojo doesn't see two ModuleScripts named
		// `jest.config` in the same folder.
		volume.writeFileSync(
			"/root/src/Client/jest.config.lua",
			"-- Auto-generated by jest-roblox (do not edit)\nreturn {}\n",
		);

		generateProjectConfigs(
			[
				{
					config: { displayName: "client", include: [], testMatch: ["**/*.spec"] },
					outputPath: "/root/src/Client/jest.config.luau",
				},
			],
			fileSystem,
		);

		expect(volume.existsSync("/root/src/Client/jest.config.luau")).toBeTrue();
		expect(volume.existsSync("/root/src/Client/jest.config.lua")).toBeFalse();
	});

	it("should preserve a user-authored jest.config.lua when no .luau stub is written", () => {
		expect.assertions(2);

		const { fileSystem, volume } = createMemoryFileSystem();

		volume.mkdirSync("/root/src/Client", { recursive: true });

		// User-authored .lua (no HEADER) — must NOT be deleted by the
		// upgrade-cleanup path. `hasUserAuthoredConfig` returns true so the
		// stub is skipped entirely.
		volume.writeFileSync("/root/src/Client/jest.config.lua", "-- user wrote this\nreturn {}");

		generateProjectConfigs(
			[
				{
					config: { displayName: "client", include: [], testMatch: ["**/*.spec"] },
					outputPath: "/root/src/Client/jest.config.luau",
				},
			],
			fileSystem,
		);

		expect(volume.existsSync("/root/src/Client/jest.config.luau")).toBeFalse();
		expect(volume.readFileSync("/root/src/Client/jest.config.lua", "utf8")).toBe(
			"-- user wrote this\nreturn {}",
		);
	});

	it("should not touch a sibling jest.config.lua when writing a non-stub config", () => {
		expect.assertions(2);

		const { fileSystem, volume } = createMemoryFileSystem();

		volume.mkdirSync("/root/src/Client", { recursive: true });

		// HEADER-prefixed legacy stub. The upgrade-cleanup path is allowed
		// to delete this when writing the new `jest.config.luau` stub, but
		// MUST NOT trigger when the caller is writing some other config
		// file in the same directory.
		volume.writeFileSync(
			"/root/src/Client/jest.config.lua",
			"-- Auto-generated by jest-roblox (do not edit)\nreturn {}\n",
		);

		generateProjectConfigs(
			[
				{
					config: { displayName: "client", include: [], testMatch: ["**/*.spec"] },
					outputPath: "/root/src/Client/other.config.luau",
				},
			],
			fileSystem,
		);

		expect(volume.existsSync("/root/src/Client/other.config.luau")).toBeTrue();
		expect(volume.existsSync("/root/src/Client/jest.config.lua")).toBeTrue();
	});
});

describe("cleanLeftoverStubs containment guard", () => {
	it("should throw when mount fsPath is absolute (escape via root)", () => {
		expect.assertions(2);

		const { fileSystem, volume } = createMemoryFileSystem({
			"/tmp/outside/jest.config.luau": "-- Auto-generated by jest-roblox (do not edit)\n",
		});

		const project = makeResolvedProject({
			rojoMounts: [{ dataModelPath: "ReplicatedStorage/evil", fsPath: "/tmp/outside" }],
		});

		expect(() => cleanLeftoverStubs([project], "/root", fileSystem)).toThrow(
			/mount fsPath must be relative/,
		);
		// Outside marker file MUST survive the failed cleanup.
		expect(volume.existsSync("/tmp/outside/jest.config.luau")).toBeTrue();
	});

	it("should throw when mount fsPath escapes root via parent segments", () => {
		expect.assertions(2);

		const { fileSystem, volume } = createMemoryFileSystem({
			"/other-package/jest.config.luau": "-- Auto-generated by jest-roblox (do not edit)\n",
		});

		const project = makeResolvedProject({
			rojoMounts: [{ dataModelPath: "ReplicatedStorage/escape", fsPath: "../other-package" }],
		});

		expect(() => cleanLeftoverStubs([project], "/root", fileSystem)).toThrow(
			/mount fsPath escapes root directory/,
		);
		// Sibling-package marker file MUST survive.
		expect(volume.existsSync("/other-package/jest.config.luau")).toBeTrue();
	});
});

describe(cleanLeftoverStubs, () => {
	it("should delete only marker-bearing files at known mount paths, leave user files alone", () => {
		expect.assertions(4);

		const { fileSystem, volume } = createMemoryFileSystem({
			"/root/dummy": "",
		});

		// Seed: one auto-generated stub via generateProjectConfigs (gets marker).
		generateProjectConfigs(
			[{ config: minimalConfig(), outputPath: "/root/out/Client/jest.config.luau" }],
			fileSystem,
		);
		// Seed: one user-authored file (no marker). volume.fromJSON replaces the
		// volume by default; write directly to keep the prior seed intact.
		volume.mkdirSync("/root/out/Shared", { recursive: true });
		volume.writeFileSync(
			"/root/out/Shared/jest.config.luau",
			"return { displayName = 'shared' }\n",
		);

		const projects: Array<ResolvedProjectConfig> = [
			makeResolvedProject({
				displayName: "client",
				rojoMounts: [{ dataModelPath: "ReplicatedStorage/Client", fsPath: "out/Client" }],
			}),
			makeResolvedProject({
				displayName: "shared",
				rojoMounts: [{ dataModelPath: "ReplicatedStorage/Shared", fsPath: "out/Shared" }],
			}),
		];

		const cleaned = cleanLeftoverStubs(projects, "/root", fileSystem);

		expect(cleaned).toHaveLength(1);
		expect(cleaned[0]).toContain("Client");
		// Auto-stub deleted.
		expect(volume.existsSync("/root/out/Client/jest.config.luau")).toBeFalse();
		// User file untouched.
		expect(volume.existsSync("/root/out/Shared/jest.config.luau")).toBeTrue();
	});

	it("should reuse the resolved real root across multiple marker-bearing mounts", () => {
		// Two marker-bearing leftover stubs in one call exercise the
		// `realRoot` lazy-init's cached-return branch.
		expect.assertions(3);

		const { fileSystem, volume } = createMemoryFileSystem({ "/root/dummy": "" });

		generateProjectConfigs(
			[
				{ config: minimalConfig(), outputPath: "/root/out/Client/jest.config.luau" },
				{ config: minimalConfig(), outputPath: "/root/out/Server/jest.config.luau" },
			],
			fileSystem,
		);

		const projects: Array<ResolvedProjectConfig> = [
			makeResolvedProject({
				displayName: "client",
				rojoMounts: [{ dataModelPath: "ReplicatedStorage/Client", fsPath: "out/Client" }],
			}),
			makeResolvedProject({
				displayName: "server",
				rojoMounts: [{ dataModelPath: "ServerStorage/Server", fsPath: "out/Server" }],
			}),
		];

		const cleaned = cleanLeftoverStubs(projects, "/root", fileSystem);

		expect(cleaned).toHaveLength(2);
		expect(volume.existsSync("/root/out/Client/jest.config.luau")).toBeFalse();
		expect(volume.existsSync("/root/out/Server/jest.config.luau")).toBeFalse();
	});
});

describe("syncStubsToShadowDirectory preserves user-authored configs", () => {
	it("should NOT delete a user-authored config from the shadow when the cache has no stub for that mount", () => {
		expect.assertions(2);

		const { fileSystem, volume } = createMemoryFileSystem();

		// Simulate the state after `prepareCoverage` has mirrored the source
		// tree into the shadow: the user's authored jest.config.luau is in
		// the shadow. The cache has a stub for a DIFFERENT mount only.
		volume.fromJSON({
			"/root/.cache/out/Server/jest.config.luau":
				"-- Auto-generated by jest-roblox (do not edit)\nreturn {}\n",
			"/shadow/out/Server/jest.config.luau": "-- old shadow content (should be replaced)\n",
			"/shadow/out/Shared/jest.config.luau": "return { displayName = 'user-authored' }\n",
		});

		const projects: Array<ResolvedProjectConfig> = [
			makeResolvedProject({
				displayName: "server",
				rojoMounts: [{ dataModelPath: "ServerStorage/Server", fsPath: "out/Server" }],
			}),
			makeResolvedProject({
				displayName: "shared",
				// User-authored config; per-mount FS check elsewhere causes
				// no cache stub to exist for this mount. The shadow already
				// has the user's file (mirrored from source by
				// prepareCoverageAsync).
				rojoMounts: [{ dataModelPath: "ReplicatedStorage/Shared", fsPath: "out/Shared" }],
			}),
		];

		syncStubsToShadowDirectory(projects, "/root/.cache", shadowAt("/shadow"), fileSystem);

		// Server: cache stub was copied in (changed).
		expect(volume.readFileSync("/shadow/out/Server/jest.config.luau", "utf8")).toContain(
			"Auto-generated",
		);

		// Shared: user file MUST survive.
		expect(volume.readFileSync("/shadow/out/Shared/jest.config.luau", "utf8")).toContain(
			"user-authored",
		);
	});
});

describe("generateProjectStubs (per-mount FS user-config detection)", () => {
	// A schema-level "is this a string-entry project" hint is insufficient:
	// a TS string-entry may not have a compiled `.luau` at the mount yet,
	// in which case we still need a generated stub. The actual gate is
	// whether a non-marker config already exists at the mount on disk.
	it("should skip stub generation only when a user-authored config actually exists at the mount", () => {
		expect.assertions(2);

		const { fileSystem, volume } = createMemoryFileSystem({
			"/root/dummy": "",
			// User-authored config exists at out/Shared but NOT at out/Server.
			// Both projects are inline-object (no userAuthoredPath) — the gate
			// is purely the FS check.
			"/root/out/Shared/jest.config.luau": "return { displayName = 'user-authored' }\n",
		});

		const sharedProject = makeResolvedProject({
			displayName: "shared",
			rojoMounts: [{ dataModelPath: "ReplicatedStorage/Shared", fsPath: "out/Shared" }],
		});
		const serverProject = makeResolvedProject({
			displayName: "server",
			rojoMounts: [{ dataModelPath: "ServerStorage/Server", fsPath: "out/Server" }],
		});

		generateProjectStubs([sharedProject, serverProject], "/root", "/root/.cache", fileSystem);

		// Shared: user file exists at mount → no cache stub.
		expect(volume.existsSync("/root/.cache/out/Shared/jest.config.luau")).toBeFalse();
		// Server: clean mount → cache stub generated.
		expect(volume.existsSync("/root/.cache/out/Server/jest.config.luau")).toBeTrue();
	});

	it("should still generate a cache stub for a string-entry project when no .luau exists at the mount (TS uncompiled / .json config)", () => {
		expect.assertions(1);

		const { fileSystem, volume } = createMemoryFileSystem({ "/root/dummy": "" });

		const stringEntryProject = makeResolvedProject({
			displayName: "shared",
			rojoMounts: [{ dataModelPath: "ReplicatedStorage/Shared", fsPath: "out/Shared" }],
		});

		generateProjectStubs([stringEntryProject], "/root", "/root/.cache", fileSystem);

		// String-entry project but mount is empty on disk — generate the
		// cache stub. Without this, a TS source whose compile hasn't run yet
		// or a .json config that has no runtime artifact would leave Jest
		// with no per-project config in DataModel.
		expect(volume.existsSync("/root/.cache/out/Shared/jest.config.luau")).toBeTrue();
	});
});

describe("cleanLeftoverStubs symlink-escape guard", () => {
	it("should throw when a mount directory is a symlink pointing outside root", () => {
		expect.assertions(2);

		const { fileSystem, volume } = createMemoryFileSystem();

		volume.mkdirSync("/root", { recursive: true });

		volume.mkdirSync("/outside/escaped", { recursive: true });
		volume.writeFileSync(
			"/outside/escaped/jest.config.luau",
			"-- Auto-generated by jest-roblox (do not edit)\n",
		);
		// In-root symlink whose target is outside the root.
		volume.symlinkSync("/outside/escaped", "/root/escaped");

		const project = makeResolvedProject({
			rojoMounts: [{ dataModelPath: "ReplicatedStorage/escaped", fsPath: "escaped" }],
		});

		expect(() => cleanLeftoverStubs([project], "/root", fileSystem)).toThrow(
			/resolves outside root via symlink/,
		);
		// Out-of-root marker file survives.
		expect(volume.existsSync("/outside/escaped/jest.config.luau")).toBeTrue();
	});
});

describe(isGeneratedStub, () => {
	it("should return true for a stub written by generateProjectConfigs (marker present)", () => {
		expect.assertions(2);

		const { fileSystem } = createMemoryFileSystem({ "/root/dummy": "" });
		const closeSpy = vi.spyOn(fileSystem, "closeSync");

		generateProjectConfigs(
			[
				{
					config: minimalConfig(),
					outputPath: "/root/out/Server/jest.config.luau",
				},
			],
			fileSystem,
		);

		expect(isGeneratedStub("/root/out/Server/jest.config.luau", fileSystem)).toBeTrue();
		expect(closeSpy).toHaveBeenCalledOnce();
	});

	it("should return false for a user-authored file without the marker", () => {
		expect.assertions(1);

		const { fileSystem } = createMemoryFileSystem({
			"/root/src/Shared/jest.config.luau": "return { displayName = 'shared' }\n",
		});

		expect(isGeneratedStub("/root/src/Shared/jest.config.luau", fileSystem)).toBeFalse();
	});

	it("should reject a file containing only a prefix of the generated marker", () => {
		expect.assertions(1);

		const { fileSystem } = createMemoryFileSystem({
			"/root/src/Shared/jest.config.luau": "-- Auto-generated by jest-roblox",
		});

		expect(isGeneratedStub("/root/src/Shared/jest.config.luau", fileSystem)).toBeFalse();
	});

	it("should reject a full-length header with different contents", () => {
		expect.assertions(1);

		const { fileSystem } = createMemoryFileSystem({
			"/root/src/Shared/jest.config.luau": "x".repeat(100),
		});

		expect(isGeneratedStub("/root/src/Shared/jest.config.luau", fileSystem)).toBeFalse();
	});

	it("should return false for a missing file", () => {
		expect.assertions(1);

		const { fileSystem } = createMemoryFileSystem();

		expect(isGeneratedStub("/root/nonexistent/jest.config.luau", fileSystem)).toBeFalse();
	});

	it("should return false when openSync throws (defensive catch)", async () => {
		// Real FS can throw EACCES, EISDIR, etc.; memfs doesn't reproduce
		// these naturally. Mock the syscall to verify the catch translates
		// the failure to `false` rather than propagating.
		expect.assertions(1);

		const { fileSystem } = createMemoryFileSystem({ "/root/file.luau": "anything" });

		const fs = await import("node:fs");
		vi.spyOn(fs.default, "openSync").mockImplementation(() => {
			throw new Error("EACCES: permission denied");
		});

		expect(isGeneratedStub("/root/file.luau", fileSystem)).toBeFalse();
	});

	it("should bake into the directory the place mounts, not the mirror beside it", () => {
		expect.assertions(2);

		const { fileSystem, volume } = createMemoryFileSystem();

		volume.mkdirSync("/root/out/client", { recursive: true });

		volume.writeFileSync("/root/out/client/jest.config.luau", "-- stub");

		const projects = [makeResolvedProject({ outDir: "out/client" })];

		syncStubsToShadowDirectory(
			projects,
			"/root",
			{
				mountedDirectory: () => "/shadow/.spine/out/client",
				root: "/shadow",
			},
			fileSystem,
		);

		expect(volume.readFileSync("/shadow/.spine/out/client/jest.config.luau", "utf8")).toBe(
			"-- stub",
		);
		expect(volume.existsSync("/shadow/out/client/jest.config.luau")).toBeFalse();
	});
});
