import isentinel from "@isentinel/eslint-config";

export default isentinel(
	{
		name: "packages/luau-ast",
		jsdoc: true,
		namedConfigs: true,
		naming: true,
		projectStructure: {
			files: ["src/**/*.ts"],
			ignores: ["src/**/*.spec.ts", "src/**/*.d.ts", "src/**/*-types.ts"],
			projectRoot: import.meta.dirname,
			structureRoot: "src",
		},
		roblox: false,
		rules: {
			"package-json/restrict-private-properties": "off",
		},
		test: {
			vitest: {
				extended: true,
				typecheck: true,
			},
		},
		type: "package",
		typescript: {
			parserOptionsTypeAware: {
				projectService: true,
			},
		},
		// `AstExpr*` mirror Luau's own AST node names — keep the vocabulary.
		unicorn: {
			nameReplacements: { expr: false },
		},
	},
	{
		name: "project/generated-wasm-module",
		// Generated by wasm/build-wasm.ts, never edited.
		ignores: ["src/luau-compiler-wasm.ts", "src/luau-parser-wasm.ts"],
	},
);
