import { fromAny } from "@total-typescript/shoehorn";

import { type } from "arktype";
import * as path from "node:path";
import process from "node:process";
import type { Mock } from "vitest";
import { assert, describe, expect, it, vi } from "vitest";

import packageJson from "../../package.json" with { type: "json" };
import type { MemoryVolume } from "../../test/mocks/memory-file-system.ts";
import { createMemoryFileSystem } from "../../test/mocks/memory-file-system.ts";
import { movableClockCollector } from "../../test/mocks/movable-clock.ts";
import type { Backend } from "../backends/interface.ts";
import type { ResolvedProjectConfig } from "../config/projects.ts";
import {
	type CliOptions,
	DEFAULT_CONFIG,
	type InlineProjectConfig,
	type ResolvedConfig,
} from "../config/schema.ts";
import { STUB_FILENAME } from "../config/stubs.ts";
import { MANIFEST_VERSION } from "../coverage-pipeline/manifest.ts";
import type { ShadowLayout } from "../coverage-pipeline/spine.ts";
import type { ExecuteResult } from "../executor.ts";
import { NOOP_RUN_PROGRESS } from "../progress/reporter.ts";
import type { TimingCollector } from "../timing/orchestration-collector.ts";
import type { JestResult } from "../types/jest-result.ts";
import type { FileSystem } from "../utils/file-system.ts";
import { normalizeWindowsPath } from "../utils/normalize-windows-path.ts";
import { runMultiProjectAsync } from "./multi.ts";
import type { RunSeams } from "./seams.ts";

const STUB_MARKER = "-- Auto-generated by jest-roblox (do not edit)\n";
const CACHE_ROOT = path.resolve("/test", ".jest-roblox", "cache");
const SYNTH_PROJECT = path.resolve(CACHE_ROOT, "synth.project.json");
/** What the stubbed coverage bake reports it split out of the place. */
const COVERAGE_BUNDLE = {
	byteLength: 24,
	fileCount: 2,
	path: "/coverage/code-bundle.json",
	stayedMounts: [],
};
const bundleSchema = type({
	mounts: type({ dataModelPath: "string[]" }).array(),
	version: "number",
});

type ExecCallback = (cause: Error | null, stdout: string, stderr: string) => void;
type RojoExec = (
	file: string,
	args: Array<string>,
	options: object,
	callback: ExecCallback,
) => void;

interface RunMocks {
	createSetupResolver: Mock<RunSeams["createSetupResolver"]>;
	execFile: Mock<RojoExec>;
	prepareCoverage: Mock<RunSeams["prepareCoverage"]>;
	resolveAllProjects: Mock<RunSeams["resolveAllProjects"]>;
	resolveBackend: Mock<RunSeams["resolveBackend"]>;
	runProjects: Mock<RunSeams["runProjects"]>;
	runTypecheck: Mock<RunSeams["runTypecheck"]>;
	tsconfigReader: Mock<RunSeams["tsconfigReader"]>;
}

function createRunMocks(): RunMocks {
	return {
		createSetupResolver: vi.fn<RunSeams["createSetupResolver"]>(),
		execFile: vi.fn<RojoExec>(),
		prepareCoverage: vi.fn<RunSeams["prepareCoverage"]>(),
		resolveAllProjects: vi.fn<RunSeams["resolveAllProjects"]>(),
		resolveBackend: vi.fn<RunSeams["resolveBackend"]>(),
		runProjects: vi.fn<RunSeams["runProjects"]>(),
		runTypecheck: vi.fn<RunSeams["runTypecheck"]>(),
		tsconfigReader: vi.fn<RunSeams["tsconfigReader"]>(),
	};
}

function toSeams(current: RunMocks): RunSeams {
	return {
		childProcess: fromAny({ execFile: current.execFile }),
		createSetupResolver: current.createSetupResolver,
		prepareCoverage: current.prepareCoverage,
		resolveAllProjects: current.resolveAllProjects,
		resolveBackend: current.resolveBackend,
		runProjects: current.runProjects,
		runTypecheck: current.runTypecheck,
		tsconfigReader: current.tsconfigReader,
	};
}

let mocks: RunMocks = createRunMocks();
let seams: RunSeams = toSeams(mocks);

function makeConfig(overrides: Partial<ResolvedConfig> = {}): ResolvedConfig {
	return {
		...DEFAULT_CONFIG,
		rojoProject: "default.project.json",
		rootDir: "/test",
		testMatch: ["**/*.spec.ts"],
		testPathIgnorePatterns: [],
		...overrides,
	};
}

function makeCli(overrides: Partial<CliOptions> = {}): CliOptions {
	return { ...overrides };
}

function makeJestResult(overrides: Partial<JestResult> = {}): JestResult {
	return {
		numFailedTests: 0,
		numPassedTests: 1,
		numPendingTests: 0,
		numTotalTests: 1,
		startTime: 1000,
		success: true,
		testResults: [],
		...overrides,
	};
}

// `runProjects` reports which projects its results are for, so a run that
// bailed can come back short. No mock here bails, so every index is present —
// stated once rather than in each mock body.
function allProjectIndices(input: { projects: ReadonlyArray<unknown> }): Array<number> {
	return input.projects.map((_project, index) => index);
}

function makeExecuteResult(overrides: Partial<ExecuteResult> = {}): ExecuteResult {
	return {
		exitCode: 0,
		output: "",
		result: makeJestResult(),
		timing: {
			executionMs: 100,
			startTime: 1000,
			testsMs: 50,
			totalMs: 200,
			uploadMs: 50,
		},
		...overrides,
	};
}

function makeBackend(kind: "open-cloud" | "studio" = "studio"): Backend {
	return {
		closeAsync: vi.fn<NonNullable<Backend["closeAsync"]>>(),
		kind,
		runTestsAsync: vi.fn<Backend["runTestsAsync"]>(),
	};
}

function makeResolvedProject(
	overrides: Partial<ResolvedProjectConfig> = {},
): ResolvedProjectConfig {
	return {
		config: makeConfig(),
		displayName: "client",
		exclude: [],
		include: ["src/client/**/*.spec.ts"],
		outDir: "out/client",
		projects: ["ReplicatedStorage/client"],
		rojoMounts: [{ dataModelPath: "ReplicatedStorage/client", fsPath: "out/client" }],
		testMatch: ["**/*.spec"],
		...overrides,
	};
}

function makeProjectEntry(name: string): InlineProjectConfig {
	return {
		test: {
			displayName: name,
			include: [`src/${name}/**/*.spec.ts`],
			outDir: `out/${name}`,
		},
	};
}

function isoNow(): string {
	const now = new Date();
	return now.toISOString();
}

function makeCoverageResult(
	overrides: {
		codeBundle?: typeof COVERAGE_BUNDLE;
		instrumentMs?: number;
		stagingMs?: number;
	} = {},
) {
	return {
		buildId: "test-build-id",
		coveragePlace: { hash: "cov-hash", path: "/coverage/game.rbxl" },
		files: {},
		instrumentMs: 0,
		manifest: {
			buildId: "test-build-id",
			files: {},
			generatedAt: isoNow(),
			instrumenterVersion: 1,
			luauRoots: [],
			nonInstrumentedFiles: {},
			placeFilePath: "/coverage/game.rbxl",
			shadowDir: ".jest-roblox/coverage",
			version: MANIFEST_VERSION,
		},
		placeFile: "/coverage/game.rbxl",
		rebuilt: true,
		stagingMs: 0,
		...overrides,
	};
}

function makeShadowLayout(): ShadowLayout {
	return {
		mountedDirectory: (sourceRelative) => path.resolve("/shadow", sourceRelative),
		root: path.resolve("/shadow"),
	};
}

function recordingTimingCollector() {
	const asyncNames: Array<string> = [];
	const names: Array<string> = [];
	const records: Array<{ elapsedMs: number; name: string }> = [];
	const timing: TimingCollector = {
		enabled: true,
		flushTimingReport: () => {
			/* unused */
		},
		profile: (name, func) => {
			names.push(name);
			return func();
		},
		profileAsync: async (name, func) => {
			asyncNames.push(name);
			return func();
		},
		profileTimed: (name, func) => {
			names.push(name);
			return { elapsedMs: 0, value: func() };
		},
		profileTimedAsync: async (name, func) => {
			asyncNames.push(name);
			return { elapsedMs: 0, value: await func() };
		},
		progress: NOOP_RUN_PROGRESS,
		record: (name, elapsedMs) => {
			records.push({ name, elapsedMs });
		},
	};
	return { asyncNames, names, records, timing };
}

function writeRojoProject(volume: MemoryVolume): void {
	const tree = {
		$className: "DataModel",
		ReplicatedStorage: { client: { $path: "out/client" } },
		ServerScriptService: { server: { $path: "out/server" } },
	};
	volume.mkdirSync("/test/out/client", { recursive: true });
	volume.mkdirSync("/test/out/server", { recursive: true });
	volume.writeFileSync("/test/default.project.json", JSON.stringify({ name: "test", tree }));
}

function writtenSynthProject(volume: MemoryVolume): { name: string; tree: unknown } {
	return fromAny(JSON.parse(String(volume.readFileSync(SYNTH_PROJECT, "utf8"))));
}

function cacheStubPath(mount: string): string {
	return path.resolve(CACHE_ROOT, mount, STUB_FILENAME);
}

function setupDefaults(configOverrides: Partial<ResolvedConfig> = {}) {
	const { fileSystem, volume } = createMemoryFileSystem();
	const config = makeConfig(configOverrides);

	mocks = createRunMocks();
	seams = toSeams(mocks);

	mocks.resolveAllProjects.mockResolvedValue([
		makeResolvedProject({ displayName: "client", outDir: "out/client" }),
		makeResolvedProject({
			displayName: "server",
			include: ["src/server/**/*.spec.ts"],
			outDir: "out/server",
			rojoMounts: [{ dataModelPath: "ServerScriptService/server", fsPath: "out/server" }],
		}),
	]);
	mocks.createSetupResolver.mockReturnValue((input) => input);
	mocks.execFile.mockImplementation((_file, args, _options, callback) => {
		const outputPath = String(args[3]);
		volume.mkdirSync(path.dirname(outputPath), { recursive: true });
		volume.writeFileSync(outputPath, "RBXL");
		callback(null, "", "");
	});
	mocks.prepareCoverage.mockResolvedValue(fromAny(makeCoverageResult()));
	mocks.resolveBackend.mockResolvedValue(makeBackend("studio"));
	mocks.runProjects.mockImplementation(async (input) => {
		return {
			backendTiming: { executionMs: 100, uploadMs: 50 },
			ranProjectIndices: allProjectIndices(input),
			results: input.projects.map(() => makeExecuteResult()),
		};
	});
	mocks.tsconfigReader.mockReturnValue(
		fromAny({
			config: { compilerOptions: { outDir: "out", rootDir: "src" } },
			path: "/test/tsconfig.json",
		}),
	);
	writeRojoProject(volume);

	return { config, fileSystem, volume };
}

function seedProjectFiles(volume: MemoryVolume): void {
	volume.mkdirSync("/test/src/client", { recursive: true });
	volume.writeFileSync("/test/src/client/a.spec.ts", "");
	volume.mkdirSync("/test/src/server", { recursive: true });
	volume.writeFileSync("/test/src/server/b.spec.ts", "");
}

function seedUserAuthoredConfigs(volume: MemoryVolume): void {
	for (const mount of ["out/client", "out/server"]) {
		volume.mkdirSync(path.resolve("/test", mount), { recursive: true });
		volume.writeFileSync(path.resolve("/test", mount, STUB_FILENAME), "return {}\n");
	}
}

function seedLeftoverStubs(volume: MemoryVolume): Array<string> {
	return ["out/client", "out/server"].map((mount) => {
		const stubPath = path.resolve("/test", mount, STUB_FILENAME);
		volume.mkdirSync(path.dirname(stubPath), { recursive: true });
		volume.writeFileSync(stubPath, `${STUB_MARKER}return {}\n`);
		return stubPath;
	});
}

function seedIndexNamesakes(volume: MemoryVolume): void {
	volume.writeFileSync("/test/tsconfig.json", "{}");
	volume.mkdirSync("/test/src/client/a", { recursive: true });
	volume.writeFileSync("/test/src/client/a/index.spec.ts", "");
	volume.mkdirSync("/test/src/client/b", { recursive: true });
	volume.writeFileSync("/test/src/client/b/index.spec.ts", "");
}

describe(runMultiProjectAsync, () => {
	it("should run all projects when no --project filter is given", async () => {
		expect.assertions(2);

		const { config, fileSystem, volume } = setupDefaults();
		seedProjectFiles(volume);

		const result = await runMultiProjectAsync({
			cli: makeCli(),
			config,
			fileSystem,
			rawProjects: [makeProjectEntry("client"), makeProjectEntry("server")],
			seams,
		});

		expect(result.mode).toBe("multi");
		expect(result.projectResults).toHaveLength(2);
	});

	it("should emit the run header to stdout before running jobs", async () => {
		expect.assertions(1);

		const { config, fileSystem, volume } = setupDefaults();
		seedProjectFiles(volume);
		const stdout = vi.spyOn(process.stdout, "write").mockReturnValue(true);

		await runMultiProjectAsync({
			cli: makeCli(),
			config,
			fileSystem,
			rawProjects: [makeProjectEntry("client")],
			seams,
		});

		expect(stdout).toHaveBeenCalledWith(expect.stringContaining(" RUN "));
	});

	it("should not emit the run header when there are no runtime jobs", async () => {
		expect.assertions(1);

		const { config, fileSystem } = setupDefaults();
		// Don't seed any test files — no runtime jobs are produced.
		const stdout = vi.spyOn(process.stdout, "write").mockReturnValue(true);

		await runMultiProjectAsync({
			cli: makeCli(),
			config,
			fileSystem,
			rawProjects: [makeProjectEntry("client")],
			seams,
		});

		expect(stdout).not.toHaveBeenCalledWith(expect.stringContaining(" RUN "));
	});

	// Workspace mode passes its volume down to project resolution, and the two
	// modes are meant to answer alike. Left off here, `createFsClassifier`
	// stats the real disk to decide which rojo mounts are directories, so a
	// project resolves against the developer's checkout rather than the run's.
	it("should resolve projects against the run's filesystem, not the real one", async () => {
		expect.assertions(1);

		const { config, fileSystem, volume } = setupDefaults();
		seedProjectFiles(volume);

		await runMultiProjectAsync({
			cli: makeCli(),
			config,
			fileSystem,
			rawProjects: [makeProjectEntry("client")],
			seams,
		});

		expect(mocks.resolveAllProjects).toHaveBeenCalledWith(
			expect.anything(),
			expect.anything(),
			expect.objectContaining({ fileSystem }),
		);
	});

	it("should filter projects by --project name", async () => {
		expect.assertions(2);

		const { config, fileSystem, volume } = setupDefaults();
		seedProjectFiles(volume);

		const result = await runMultiProjectAsync({
			cli: makeCli({ project: ["client"] }),
			config,
			fileSystem,
			rawProjects: [makeProjectEntry("client"), makeProjectEntry("server")],
			seams,
		});

		expect(result.projectResults).toHaveLength(1);
		expect(result.projectResults[0]!.displayName).toBe("client");
	});

	describe("coverage display filter", () => {
		it("should expose a source-twin filter for positional files", async () => {
			expect.assertions(1);

			const { config, fileSystem, volume } = setupDefaults();
			seedProjectFiles(volume);

			const result = await runMultiProjectAsync({
				cli: makeCli({ files: ["src/client/a.spec.ts"] }),
				config,
				fileSystem,
				rawProjects: [makeProjectEntry("client"), makeProjectEntry("server")],
				seams,
			});

			const twin = normalizeWindowsPath(path.resolve("/test", "src/client/a.ts"));

			expect(result.coverageDisplayFilter!(twin)).toBeTrue();
		});

		it("should twin the matched runtime files for a testPathPattern run", async () => {
			expect.assertions(1);

			const { config, fileSystem, volume } = setupDefaults({ testPathPattern: "a" });
			seedProjectFiles(volume);

			const result = await runMultiProjectAsync({
				cli: makeCli(),
				config,
				fileSystem,
				rawProjects: [makeProjectEntry("client"), makeProjectEntry("server")],
				seams,
			});

			const twin = normalizeWindowsPath(path.resolve("/test", "src/client/a.ts"));

			expect(result.coverageDisplayFilter!(twin)).toBeTrue();
		});

		it("should expose a project-scope filter for a --project run", async () => {
			expect.assertions(1);

			const { config, fileSystem, volume } = setupDefaults();
			seedProjectFiles(volume);

			const result = await runMultiProjectAsync({
				cli: makeCli({ project: ["client"] }),
				config,
				fileSystem,
				rawProjects: [makeProjectEntry("client"), makeProjectEntry("server")],
				seams,
			});

			expect(result.coverageDisplayFilter).toBeTypeOf("function");
		});

		it("should leave the filter undefined on a bare run", async () => {
			expect.assertions(1);

			const { config, fileSystem, volume } = setupDefaults();
			seedProjectFiles(volume);

			const result = await runMultiProjectAsync({
				cli: makeCli(),
				config,
				fileSystem,
				rawProjects: [makeProjectEntry("client"), makeProjectEntry("server")],
				seams,
			});

			expect(result.coverageDisplayFilter).toBeUndefined();
		});

		it("should leave the filter undefined for --project when no static roots derive", async () => {
			expect.assertions(1);

			const { config, fileSystem, volume } = setupDefaults();
			seedProjectFiles(volume);
			mocks.resolveAllProjects.mockResolvedValue([
				makeResolvedProject({ displayName: "client", include: ["**/*.spec.ts"] }),
			]);

			const result = await runMultiProjectAsync({
				cli: makeCli({ project: ["client"] }),
				config,
				fileSystem,
				rawProjects: [makeProjectEntry("client")],
				seams,
			});

			expect(result.coverageDisplayFilter).toBeUndefined();
		});
	});

	it("should throw on unknown --project displayName", async () => {
		expect.assertions(1);

		const { config, fileSystem, volume } = setupDefaults();
		seedProjectFiles(volume);

		await expect(
			runMultiProjectAsync({
				cli: makeCli({ project: ["nonexistent"] }),
				config,
				fileSystem,
				rawProjects: [makeProjectEntry("client")],
				seams,
			}),
		).rejects.toThrow("Unknown project name(s): nonexistent. Available: client, server");
	});

	it("should throw when Rojo project schema is invalid", async () => {
		expect.assertions(1);

		const { config, fileSystem, volume } = setupDefaults();

		// Overwrite with an invalid Rojo project (missing required name)
		volume.writeFileSync(
			"/test/default.project.json",
			JSON.stringify({ tree: "not-an-object" }),
		);

		await expect(
			runMultiProjectAsync({
				cli: makeCli(),
				config,
				fileSystem,
				rawProjects: [makeProjectEntry("client")],
				seams,
			}),
		).rejects.toThrow(/Invalid Rojo project/);
	});

	it("should default rojoProject to default.project.json when not configured", async () => {
		expect.assertions(1);

		const { config, fileSystem, volume } = setupDefaults({ rojoProject: undefined });
		seedProjectFiles(volume);

		const result = await runMultiProjectAsync({
			cli: makeCli(),
			config,
			fileSystem,
			rawProjects: [makeProjectEntry("client")],
			seams,
		});

		expect(result.mode).toBe("multi");
	});

	it("should default rojoProject for the open-cloud synthesizer build when unset", async () => {
		expect.assertions(1);

		const { config, fileSystem, volume } = setupDefaults({ rojoProject: undefined });
		mocks.resolveBackend.mockResolvedValueOnce(makeBackend("open-cloud"));
		seedProjectFiles(volume);

		await runMultiProjectAsync({
			cli: makeCli(),
			config,
			fileSystem,
			rawProjects: [makeProjectEntry("client")],
			seams,
		});

		expect(writtenSynthProject(volume).tree).toStrictEqual(
			expect.objectContaining({ $className: "DataModel" }),
		);
	});

	/**
	 * The bundle path an open-cloud place build writes to, which exists exactly
	 * when the run asked for a Harness Place. Beside the place it was split
	 * from and named after it, which is `place-builder`'s rule rather than a
	 * path any caller here names.
	 */
	function bundleFile(config: ResolvedConfig): string {
		return path.resolve(config.rootDir, "game.code-bundle.json");
	}

	/**
	 * A rojo project whose one mount sits under the run's staging directory.
	 */
	function writeStagedMount(volume: MemoryVolume): void {
		// Under the run's own staging directory, which is a Code Root whatever
		// the projects resolve to.
		const mountDirectory = path.resolve(CACHE_ROOT, "mount");
		volume.mkdirSync(mountDirectory, { recursive: true });
		volume.writeFileSync(path.join(mountDirectory, "thing.luau"), "return 1");
		volume.writeFileSync(
			"/test/default.project.json",
			JSON.stringify({
				name: "test",
				tree: {
					$className: "DataModel",
					ReplicatedStorage: {
						client: { $path: "out/client" },
						Mount: { $path: normalizeWindowsPath(mountDirectory) },
					},
					ServerScriptService: { server: { $path: "out/server" } },
				},
			}),
		);
	}

	/**
	 * One coverage run, whose place the coverage bake builds rather than the
	 * run.
	 */
	async function runCoverageAsync(kind: "open-cloud" | "studio"): Promise<void> {
		const { config, fileSystem, volume } = setupDefaults({ collectCoverage: true });
		mocks.prepareCoverage.mockResolvedValue(
			fromAny(makeCoverageResult({ codeBundle: COVERAGE_BUNDLE })),
		);
		mocks.resolveBackend.mockResolvedValueOnce(makeBackend(kind));
		seedProjectFiles(volume);

		await runMultiProjectAsync({
			cli: makeCli(),
			config,
			fileSystem,
			rawProjects: [makeProjectEntry("client")],
			seams,
		});
	}

	async function runOpenCloudAsync(
		configOverrides: Partial<ResolvedConfig> = {},
	): Promise<{ config: ResolvedConfig; volume: MemoryVolume }> {
		const { config, fileSystem, volume } = setupDefaults(configOverrides);
		mocks.resolveBackend.mockResolvedValueOnce(makeBackend("open-cloud"));
		seedProjectFiles(volume);

		await runMultiProjectAsync({
			cli: makeCli(),
			config,
			fileSystem,
			rawProjects: [makeProjectEntry("client")],
			seams,
		});
		return { config, volume };
	}

	it("should split a code bundle out of an open-cloud place by default", async () => {
		expect.assertions(1);

		const { config, volume } = await runOpenCloudAsync();

		expect(volume.existsSync(bundleFile(config))).toBeTrue();
	});

	it("should take the mounts inside a code root out of the place", async () => {
		expect.assertions(2);

		const { config, fileSystem, volume } = setupDefaults();
		writeStagedMount(volume);
		mocks.resolveBackend.mockResolvedValueOnce(makeBackend("open-cloud"));
		seedProjectFiles(volume);

		await runMultiProjectAsync({
			cli: makeCli(),
			config,
			fileSystem,
			rawProjects: [makeProjectEntry("client")],
			seams,
		});

		const bundle = bundleSchema.assert(
			JSON.parse(String(volume.readFileSync(bundleFile(config), "utf8"))),
		);

		// Every mount here resolves inside a Code Root: the compiled output
		// each project declares, the generated stub beneath it, and the one
		// under the staging directory.
		expect(bundle.mounts.map((mount) => mount.dataModelPath)).toStrictEqual([
			["ReplicatedStorage", "Mount"],
			["ReplicatedStorage", "client"],
			["ServerScriptService", "server"],
			["ReplicatedStorage", "client", "jest.config"],
			["ServerScriptService", "server", "jest.config"],
		]);
		// They all went into the bundle, so the harness project declares nothing
		// under either service — the services themselves stay, because rojo
		// builds one whether or not the project puts anything there.
		expect(writtenSynthProject(volume).tree).toStrictEqual({
			$className: "DataModel",
			ReplicatedStorage: {},
			ServerScriptService: {},
		});
	});

	/**
	 * Story 24 on the non-coverage path: the harness never held the edited
	 * file, so the key over its inputs cannot have moved and the rojo build is
	 * skipped along with the upload.
	 */
	it("should reuse the harness across an edit to the code that travels", async () => {
		expect.assertions(2);

		const { config, fileSystem, volume } = setupDefaults();
		const mountDirectory = path.resolve(CACHE_ROOT, "mount");
		writeStagedMount(volume);
		seedProjectFiles(volume);

		async function runAsync(): Promise<void> {
			mocks.resolveBackend.mockResolvedValueOnce(makeBackend("open-cloud"));
			await runMultiProjectAsync({
				cli: makeCli(),
				config,
				fileSystem,
				rawProjects: [makeProjectEntry("client")],
				seams,
			});
		}

		await runAsync();
		volume.writeFileSync(path.join(mountDirectory, "thing.luau"), "return 2");
		await runAsync();

		expect(mocks.execFile).toHaveBeenCalledOnce();
		// The bundle is written on every run, reused place or not: a reused
		// harness never held this run's code.
		expect(String(volume.readFileSync(bundleFile(config), "utf8"))).toContain("return 2");
	});

	it("should ask the coverage build for a harness only on open cloud", async () => {
		expect.assertions(2);

		await runCoverageAsync("open-cloud");

		expect(mocks.prepareCoverage.mock.calls[0]![1]!.codeRoots).toBeDefined();

		await runCoverageAsync("studio");

		// A Studio backend runs the place a caller opens, so code taken out of
		// it would be code that never arrives.
		expect(mocks.prepareCoverage.mock.calls[0]![1]!.codeRoots).toBeUndefined();
	});

	it("should hand the coverage build's own bundle to the backend", async () => {
		expect.assertions(1);

		await runCoverageAsync("open-cloud");

		// A coverage run builds its place inside staging, so the bundle the
		// backend uploads is the one that build split out — never the one the
		// non-coverage place build would have written later.
		expect(mocks.runProjects.mock.calls[0]![0].codeBundle).toStrictEqual(COVERAGE_BUNDLE);
	});

	it("should build the whole place under --no-binary-input", async () => {
		expect.assertions(1);

		const { config, volume } = await runOpenCloudAsync({ binaryInput: false });

		expect(volume.existsSync(bundleFile(config))).toBeFalse();
	});

	it("should call buildWithRojoAsync when coverage is disabled and backend is open-cloud", async () => {
		expect.assertions(5);

		const { config, fileSystem, volume } = setupDefaults();
		const recorded = recordingTimingCollector();
		const backend = makeBackend("open-cloud");
		// Studio skips the place build (it uses the runtime injector).
		// Place build only runs for open-cloud + no-coverage.
		mocks.resolveBackend.mockResolvedValueOnce(backend);
		seedProjectFiles(volume);

		await runMultiProjectAsync({
			cli: makeCli(),
			config,
			fileSystem,
			rawProjects: [makeProjectEntry("client")],
			seams,
			timing: recorded.timing,
		});

		expect({
			buildCalls: mocks.execFile.mock.calls.length,
			projectPath: mocks.execFile.mock.calls[0]![1][1],
		}).toStrictEqual({
			buildCalls: 1,
			projectPath: expect.stringContaining("synth.project.json"),
		});
		expect(writtenSynthProject(volume).name).toBe("test");
		expect({
			asyncNames: recorded.asyncNames,
			names: recorded.names,
			records: recorded.records,
		}).toStrictEqual({
			// The backend leads: staging decides whether the place holds
			// the run's code, and only the backend answers that. The plan
			// leads both, so a run with nothing to do reaches neither.
			asyncNames: [
				"resolveAllProjects",
				"resolveBackend",
				"prepareCoverage",
				"buildOpenCloudPlace",
				"runProjects",
			],
			names: [
				"loadRojoTree",
				"resolveSetupFilePaths",
				"selectProjects",
				"collectPendingJobs",
				"cleanLeftoverStubs",
				"generateProjectStubs",
			],
			records: [],
		});
		expect(volume.existsSync(cacheStubPath("out/client"))).toBeTrue();

		const runInput = mocks.runProjects.mock.calls[0]![0];

		expect({
			backend: runInput.backend,
			deferFormatting: runInput.deferFormatting,
			parallel: runInput.parallel,
			project: {
				displayColor: runInput.projects[0]!.displayColor,
				displayName: runInput.projects[0]!.displayName,
				testFiles: runInput.projects[0]!.testFiles,
			},
			timing: runInput.timing,
			version: runInput.version,
		}).toStrictEqual({
			backend,
			deferFormatting: true,
			parallel: undefined,
			project: {
				displayColor: undefined,
				displayName: "client",
				testFiles: ["src/client/a.spec.ts"],
			},
			timing: recorded.timing,
			version: packageJson.version,
		});
	});

	it("should skip buildWithRojoAsync entirely when backend is studio", async () => {
		expect.assertions(2);

		const { config, fileSystem, volume } = setupDefaults();
		// Default backend in setupDefaults is studio; reaffirm explicitly.
		mocks.resolveBackend.mockResolvedValueOnce(makeBackend("studio"));
		seedProjectFiles(volume);

		await runMultiProjectAsync({
			cli: makeCli(),
			config,
			fileSystem,
			rawProjects: [makeProjectEntry("client")],
			seams,
		});

		expect(mocks.execFile).not.toHaveBeenCalled();
		expect(volume.existsSync(SYNTH_PROJECT)).toBeFalse();
	});

	it("should skip buildWithRojoAsync and prepare coverage when collectCoverage is true", async () => {
		expect.assertions(3);

		const { config, fileSystem, volume } = setupDefaults({ collectCoverage: true });
		mocks.prepareCoverage.mockResolvedValue(fromAny(makeCoverageResult()));
		seedProjectFiles(volume);

		const result = await runMultiProjectAsync({
			cli: makeCli(),
			config,
			fileSystem,
			rawProjects: [makeProjectEntry("client")],
			seams,
		});

		expect(mocks.execFile).not.toHaveBeenCalled();
		expect(mocks.prepareCoverage).toHaveBeenCalledOnce();
		expect(result.coverageMs).toBeGreaterThanOrEqual(0);
	});

	it("should report the coverage place build as staging, not as coverage", async () => {
		expect.assertions(2);

		const { config, fileSystem, volume } = setupDefaults({ collectCoverage: true });
		// Frozen: the stub sweep must contribute nothing, so the only staging
		// left is the place build the coverage bake reports.
		const clock = movableClockCollector(1_000);
		mocks.prepareCoverage.mockResolvedValue(
			fromAny(makeCoverageResult({ instrumentMs: 120, stagingMs: 250 })),
		);
		seedProjectFiles(volume);

		const result = await runMultiProjectAsync({
			cli: makeCli(),
			config,
			fileSystem,
			rawProjects: [makeProjectEntry("client")],
			seams,
			timing: clock.timing,
		});

		expect(result.coverageMs).toBe(120);
		expect(result.stagingMs).toBe(250);
	});

	it("should measure the stub staging as stagingMs", async () => {
		expect.assertions(1);

		const { config, fileSystem, volume } = setupDefaults();
		seedProjectFiles(volume);

		// Studio backend: no place build, so the stub sweep is the whole of
		// staging.
		mocks.resolveAllProjects.mockResolvedValue([makeResolvedProject()]);
		const clock = movableClockCollector(1_000);
		const slowFileSystem: FileSystem = {
			...fileSystem,
			writeFileSync: (file, data, options) => {
				clock.advance(40);
				fileSystem.writeFileSync(file, data, options);
			},
		};

		const result = await runMultiProjectAsync({
			cli: makeCli(),
			config,
			fileSystem: slowFileSystem,
			rawProjects: [makeProjectEntry("client")],
			seams,
			timing: clock.timing,
		});

		expect(result.stagingMs).toBe(40);
	});

	it("should measure the open-cloud place build as stagingMs", async () => {
		expect.assertions(2);

		const { config, fileSystem, volume } = setupDefaults();

		mocks.resolveBackend.mockResolvedValue(makeBackend("open-cloud"));
		seedProjectFiles(volume);

		// The build is synchronous, so the only way to give it a measurable
		// duration is to move the clock from inside it. Two counters, moved by
		// different amounts: a phase duration comes off the collector's clock,
		// while `startTime` stamps the wall clock the "Start at" line renders.
		const clock = movableClockCollector(0);
		let wallMs = 1_000;
		vi.spyOn(Date, "now").mockImplementation(() => wallMs);
		mocks.execFile.mockImplementation((_file, args, _options, callback) => {
			clock.advance(250);
			wallMs += 900;
			const outputPath = String(args[3]);
			volume.mkdirSync(path.dirname(outputPath), { recursive: true });
			volume.writeFileSync(outputPath, "RBXL");
			callback(null, "", "");
		});
		const result = await runMultiProjectAsync({
			cli: makeCli(),
			config,
			fileSystem,
			rawProjects: [makeProjectEntry("client")],
			seams,
			timing: clock.timing,
		});

		expect(result.stagingMs).toBe(250);
		// The dispatch window must open after the build, or the reported total
		// would count the build twice.
		expect(mocks.runProjects.mock.calls[0]![0].startTime).toBe(1_900);
	});

	it("should record the resolved projects in the coverage artifacts", async () => {
		expect.assertions(1);

		const { config, fileSystem, volume } = setupDefaults({ collectCoverage: true });
		seedProjectFiles(volume);

		const result = await runMultiProjectAsync({
			cli: makeCli(),
			config,
			fileSystem,
			rawProjects: [makeProjectEntry("client")],
			seams,
		});

		expect(result.coverageArtifacts!.projects).toStrictEqual(
			expect.arrayContaining([
				expect.objectContaining({
					displayName: "client",
					projectDataModelPath: "ReplicatedStorage/client",
				}),
			]),
		);
	});

	it("should hand coverage both halves of the stub bake", async () => {
		expect.assertions(2);

		const { config, fileSystem, volume } = setupDefaults({ collectCoverage: true });
		seedProjectFiles(volume);

		await runMultiProjectAsync({
			cli: makeCli(),
			config,
			fileSystem,
			rawProjects: [makeProjectEntry("client")],
			seams,
		});

		const shadow = makeShadowLayout();
		const { bake } = mocks.prepareCoverage.mock.calls[0]![1]!;

		// Both halves, together: a hook whose writes nothing declares gets
		// them swept back out by the shadow's own orphan reconcile.
		expect(bake!.isBakeOwned(cacheStubPath("out/client"))).toBeTrue();

		const didWrite = bake!.run(shadow);

		expect({
			didWrite,
			mirrored: volume.existsSync(path.resolve(shadow.root, "out/client", STUB_FILENAME)),
		}).toStrictEqual({ didWrite: true, mirrored: true });
	});

	it("should instrument against the derived universe when no coverage globs are set", async () => {
		expect.assertions(1);

		const { config, fileSystem, volume } = setupDefaults({ collectCoverage: true });
		seedProjectFiles(volume);

		await runMultiProjectAsync({
			cli: makeCli(),
			config,
			fileSystem,
			rawProjects: [makeProjectEntry("client")],
			seams,
		});

		// The report narrows by the derived set whether or not the user set
		// `collectCoverageFrom`; instrumentation has to see the same value, or
		// the default path probes files no report will ever ask about.
		expect(mocks.prepareCoverage).toHaveBeenCalledWith(
			expect.anything(),
			expect.objectContaining({
				coverageInclude: expect.arrayContaining(["src/client/**/*.ts"]),
			}),
		);
	});

	it("should NOT bake stubs into the coverage place for the studio-cli backend", async () => {
		// studio-cli drives the plugin's Run-mode runner, which injects
		// `jest.config` ModuleScripts from the payload at runtime. Baking them
		// into the instrumented place too would make the runner collide with an
		// already-present `jest.config` ("Structural collision …"). So coverage
		// prep must skip the stub bake for this backend and let
		// runtime injection be the sole config source.
		expect.assertions(2);

		const { config, fileSystem, volume } = setupDefaults({
			backend: "studio-cli",
			collectCoverage: true,
		});
		mocks.prepareCoverage.mockImplementation(async (_config, options) => {
			// The absent bake *is* the contract: no hook, no stub in the place.
			expect(options!.bake).toBeUndefined();

			return fromAny(makeCoverageResult());
		});
		seedProjectFiles(volume);

		await runMultiProjectAsync({
			cli: makeCli(),
			config,
			fileSystem,
			rawProjects: [makeProjectEntry("client")],
			seams,
		});

		expect(mocks.prepareCoverage).toHaveBeenCalledOnce();
	});

	it("should return validationExitCode 2 with message when no test files found", async () => {
		expect.assertions(3);

		const { config, fileSystem } = setupDefaults();
		// Don't seed any test files

		const result = await runMultiProjectAsync({
			cli: makeCli(),
			config,
			fileSystem,
			rawProjects: [makeProjectEntry("client")],
			seams,
		});

		expect(result.validationExitCode).toBe(2);
		expect(result.validationMessage).toBe("No test files found in any project\n");
		expect(result.projectResults).toHaveLength(0);
	});

	it("should return empty projectResults without validation error when passWithNoTests", async () => {
		expect.assertions(2);

		const { config, fileSystem } = setupDefaults({ passWithNoTests: true });
		// Don't seed any test files

		const result = await runMultiProjectAsync({
			cli: makeCli(),
			config,
			fileSystem,
			rawProjects: [makeProjectEntry("client")],
			seams,
		});

		expect(result.validationExitCode).toBeUndefined();
		expect(result.projectResults).toHaveLength(0);
	});

	it("should run typecheck across all projects with deduplicated files", async () => {
		expect.assertions(5);

		const { config, fileSystem, volume } = setupDefaults({
			timeout: 654_321,
			typecheck: {
				enabled: true,
				ignoreSourceErrors: true,
				spawnTimeout: 4321,
				tsconfig: "tsconfig.root.json",
			},
		});

		const recorded = recordingTimingCollector();
		mocks.runTypecheck.mockResolvedValue(makeJestResult());
		volume.mkdirSync("/test/src/client", { recursive: true });
		volume.writeFileSync("/test/src/client/a.spec.ts", "");
		volume.writeFileSync("/test/src/client/a.spec-d.ts", "");
		volume.mkdirSync("/test/src/server", { recursive: true });
		volume.writeFileSync("/test/src/server/b.spec.ts", "");

		// Both projects produce the same type-test file via deduplication.
		mocks.resolveAllProjects.mockResolvedValue([
			makeResolvedProject({
				displayName: "client",
				include: ["src/client/**/*.spec.ts", "src/client/**/*.spec-d.ts"],
			}),
			makeResolvedProject({
				displayName: "server",
				include: ["src/server/**/*.spec.ts"],
			}),
		]);

		const result = await runMultiProjectAsync({
			cli: makeCli(),
			config,
			fileSystem,
			rawProjects: [makeProjectEntry("client"), makeProjectEntry("server")],
			seams,
			timing: recorded.timing,
		});

		expect(mocks.runTypecheck).toHaveBeenCalledExactlyOnceWith({
			files: ["src/client/a.spec-d.ts"],
			ignoreSourceErrors: true,
			rootDir: "/test",
			spawnTimeout: 4321,
			timeout: 654_321,
			tsconfig: "tsconfig.root.json",
		});
		expect(result.typecheckResult).toBeDefined();
		expect(recorded.records).toHaveLength(1);
		expect(recorded.records[0]!.name).toBe("runTypecheck");
		expect(recorded.records[0]!.elapsedMs).toBeGreaterThan(0);
	});

	it("should run the typecheck pass concurrently with the runtime run", async () => {
		expect.assertions(2);

		const { config, fileSystem, volume } = setupDefaults({ typecheck: { enabled: true } });

		volume.mkdirSync("/test/src/client", { recursive: true });
		volume.writeFileSync("/test/src/client/a.spec.ts", "");
		volume.writeFileSync("/test/src/client/a.spec-d.ts", "");
		mocks.resolveAllProjects.mockResolvedValue([
			makeResolvedProject({
				displayName: "client",
				include: ["src/client/**/*.spec.ts", "src/client/**/*.spec-d.ts"],
			}),
		]);

		// A rendezvous: each side proceeds only once the other has started, so
		// the run completes solely when the two overlap. A strictly-after pass
		// would leave one side awaiting a signal that never fires (it hangs).
		let signalRuntimeStarted!: () => void;
		let signalTypecheckStarted!: () => void;
		const runtimeStarted = new Promise<void>((resolve) => {
			signalRuntimeStarted = resolve;
		});
		const typecheckStarted = new Promise<void>((resolve) => {
			signalTypecheckStarted = resolve;
		});
		mocks.runProjects.mockImplementation(async (input) => {
			signalRuntimeStarted();
			await typecheckStarted;
			return {
				backendTiming: { executionMs: 100, uploadMs: 50 },
				ranProjectIndices: allProjectIndices(input),
				results: input.projects.map(() => makeExecuteResult()),
			};
		});
		mocks.runTypecheck.mockImplementation(async () => {
			signalTypecheckStarted();
			await runtimeStarted;
			return makeJestResult();
		});

		const result = await runMultiProjectAsync({
			cli: makeCli(),
			config,
			fileSystem,
			rawProjects: [makeProjectEntry("client")],
			seams,
		});

		expect(result.typecheckResult).toBeDefined();
		expect(result.projectResults).toHaveLength(1);
	});

	it("should check projects with distinct typecheck tsconfigs against their own", async () => {
		expect.assertions(3);

		const { config, fileSystem, volume } = setupDefaults({ typecheck: { enabled: true } });

		mocks.runTypecheck.mockResolvedValue(makeJestResult());
		volume.mkdirSync("/test/src/client", { recursive: true });
		volume.writeFileSync("/test/src/client/a.spec-d.ts", "");
		volume.mkdirSync("/test/src/server", { recursive: true });
		volume.writeFileSync("/test/src/server/b.spec-d.ts", "");
		mocks.resolveAllProjects.mockResolvedValue([
			makeResolvedProject({
				displayName: "client",
				include: ["src/client/**/*.spec.ts"],
				typecheck: { tsconfig: "tsconfig.client.json" },
			}),
			makeResolvedProject({
				displayName: "server",
				include: ["src/server/**/*.spec.ts"],
				outDir: "out/server",
				rojoMounts: [{ dataModelPath: "ServerScriptService/server", fsPath: "out/server" }],
				typecheck: { tsconfig: "tsconfig.server.json" },
			}),
		]);

		await runMultiProjectAsync({
			cli: makeCli(),
			config,
			fileSystem,
			rawProjects: [makeProjectEntry("client"), makeProjectEntry("server")],
			seams,
		});

		expect(mocks.runTypecheck).toHaveBeenCalledTimes(2);
		expect(mocks.runTypecheck).toHaveBeenCalledWith(
			expect.objectContaining({
				files: ["src/client/a.spec-d.ts"],
				tsconfig: "tsconfig.client.json",
			}),
		);
		expect(mocks.runTypecheck).toHaveBeenCalledWith(
			expect.objectContaining({
				files: ["src/server/b.spec-d.ts"],
				tsconfig: "tsconfig.server.json",
			}),
		);
	});

	it("should derive spec-d type tests from a runtime-only include", async () => {
		expect.assertions(1);

		const { config, fileSystem, volume } = setupDefaults({ typecheck: { enabled: true } });

		mocks.runTypecheck.mockResolvedValue(makeJestResult());
		volume.mkdirSync("/test/src/client", { recursive: true });
		volume.writeFileSync("/test/src/client/a.spec.ts", "");
		volume.writeFileSync("/test/src/client/a.spec-d.ts", "");
		mocks.resolveAllProjects.mockResolvedValue([
			makeResolvedProject({
				displayName: "client",
				include: ["src/client/**/*.spec.ts"],
			}),
		]);

		await runMultiProjectAsync({
			cli: makeCli(),
			config,
			fileSystem,
			rawProjects: [makeProjectEntry("client")],
			seams,
		});

		expect(mocks.runTypecheck).toHaveBeenCalledWith(
			expect.objectContaining({
				files: expect.arrayContaining([expect.stringMatching(/a\.spec-d\.ts$/)]),
			}),
		);
	});

	it("should run typecheck-only without resolving a backend or runtime jobs", async () => {
		expect.assertions(3);

		const { config, fileSystem, volume } = setupDefaults({
			typecheck: { enabled: true, only: true },
		});

		mocks.runTypecheck.mockResolvedValue(makeJestResult());
		volume.mkdirSync("/test/src/client", { recursive: true });
		volume.writeFileSync("/test/src/client/a.spec-d.ts", "");
		mocks.resolveAllProjects.mockResolvedValue([
			makeResolvedProject({
				displayName: "client",
				include: ["src/client/**/*.spec-d.ts"],
			}),
		]);

		const result = await runMultiProjectAsync({
			cli: makeCli(),
			config,
			fileSystem,
			rawProjects: [makeProjectEntry("client")],
			seams,
		});

		// The type-only short-circuit runs pure-local tsgo: no backend resolved,
		// no place built, no Roblox jobs dispatched.
		expect(mocks.resolveBackend).not.toHaveBeenCalled();
		expect(mocks.runProjects).not.toHaveBeenCalled();
		expect(result.typecheckResult).toBeDefined();
	});

	it("should keep the runtime path when only one selected project is typecheck-only", async () => {
		expect.assertions(2);

		const { config, fileSystem, volume } = setupDefaults({ typecheck: { enabled: true } });
		seedProjectFiles(volume);
		mocks.resolveAllProjects.mockResolvedValue([
			makeResolvedProject({
				displayName: "client",
				typecheck: { enabled: true, only: true },
			}),
			makeResolvedProject({
				displayName: "server",
				include: ["src/server/**/*.spec.ts"],
				typecheck: { enabled: true, only: false },
			}),
		]);

		await runMultiProjectAsync({
			cli: makeCli(),
			config,
			fileSystem,
			rawProjects: [makeProjectEntry("client"), makeProjectEntry("server")],
			seams,
		});

		expect(mocks.resolveBackend).toHaveBeenCalledOnce();
		expect(mocks.runProjects).toHaveBeenCalledOnce();
	});

	it("should carry the configured timeout into the typecheck-only pass", async () => {
		expect.assertions(1);

		const { config, fileSystem, volume } = setupDefaults({
			timeout: 900_000,
			typecheck: { enabled: true, only: true },
		});

		mocks.runTypecheck.mockResolvedValue(makeJestResult());
		volume.mkdirSync("/test/src/client", { recursive: true });
		volume.writeFileSync("/test/src/client/a.spec-d.ts", "");
		mocks.resolveAllProjects.mockResolvedValue([
			makeResolvedProject({
				displayName: "client",
				include: ["src/client/**/*.spec-d.ts"],
			}),
		]);

		await runMultiProjectAsync({
			cli: makeCli(),
			config,
			fileSystem,
			rawProjects: [makeProjectEntry("client")],
			seams,
		});

		expect(mocks.runTypecheck).toHaveBeenCalledWith(
			expect.objectContaining({ timeout: 900_000 }),
		);
	});

	it("should return validationExitCode 2 on a typecheck-only run that finds no type tests", async () => {
		expect.assertions(3);

		const { config, fileSystem } = setupDefaults({ typecheck: { enabled: true, only: true } });
		// No spec-d files seeded — the project produces no Type Tests.
		mocks.resolveAllProjects.mockResolvedValue([
			makeResolvedProject({
				displayName: "client",
				include: ["src/client/**/*.spec-d.ts"],
			}),
		]);

		const result = await runMultiProjectAsync({
			cli: makeCli(),
			config,
			fileSystem,
			rawProjects: [makeProjectEntry("client")],
			seams,
		});

		expect(result.validationExitCode).toBe(2);
		expect(result.validationMessage).toBe("No test files found in any project\n");
		expect(mocks.resolveBackend).not.toHaveBeenCalled();
	});

	it("should pass with no tests on a typecheck-only run when passWithNoTests is set", async () => {
		expect.assertions(2);

		const { config, fileSystem } = setupDefaults({
			passWithNoTests: true,
			typecheck: { enabled: true, only: true },
		});
		// No spec-d files seeded — the project produces no Type Tests.
		mocks.resolveAllProjects.mockResolvedValue([
			makeResolvedProject({
				displayName: "client",
				include: ["src/client/**/*.spec-d.ts"],
			}),
		]);

		const result = await runMultiProjectAsync({
			cli: makeCli(),
			config,
			fileSystem,
			rawProjects: [makeProjectEntry("client")],
			seams,
		});

		expect(result.validationExitCode).toBeUndefined();
		expect(result.projectResults).toHaveLength(0);
	});

	it("should forward test.typecheck.ignoreSourceErrors to the typecheck runner", async () => {
		expect.assertions(1);

		const { config, fileSystem, volume } = setupDefaults({
			typecheck: { enabled: true, ignoreSourceErrors: true, only: true },
		});

		mocks.runTypecheck.mockResolvedValue(makeJestResult());
		volume.mkdirSync("/test/src/client", { recursive: true });
		volume.writeFileSync("/test/src/client/a.spec-d.ts", "");
		mocks.resolveAllProjects.mockResolvedValue([
			makeResolvedProject({
				displayName: "client",
				include: ["src/client/**/*.spec-d.ts"],
			}),
		]);

		await runMultiProjectAsync({
			cli: makeCli(),
			config,
			fileSystem,
			rawProjects: [makeProjectEntry("client")],
			seams,
		});

		expect(mocks.runTypecheck).toHaveBeenCalledWith(
			expect.objectContaining({ ignoreSourceErrors: true }),
		);
	});

	it("should not discover type tests when include is set but typecheck is disabled", async () => {
		expect.assertions(1);

		const { config, fileSystem, volume } = setupDefaults({
			typecheck: { include: ["src/client/**/*.spec-d.ts"] },
		});

		volume.mkdirSync("/test/src/client", { recursive: true });
		volume.writeFileSync("/test/src/client/a.spec.ts", "");
		volume.writeFileSync("/test/src/client/a.spec-d.ts", "");
		mocks.resolveAllProjects.mockResolvedValue([
			makeResolvedProject({ displayName: "client", include: ["src/client/**/*.spec.ts"] }),
		]);

		await runMultiProjectAsync({
			cli: makeCli(),
			config,
			fileSystem,
			rawProjects: [makeProjectEntry("client")],
			seams,
		});

		expect(mocks.runTypecheck).not.toHaveBeenCalled();
	});

	it("should use an explicit typecheck include instead of deriving", async () => {
		expect.assertions(1);

		const { config, fileSystem, volume } = setupDefaults({
			typecheck: { enabled: true, include: ["src/shared/**/*.spec-d.ts"] },
		});

		mocks.runTypecheck.mockResolvedValue(makeJestResult());
		volume.mkdirSync("/test/src/client", { recursive: true });
		volume.writeFileSync("/test/src/client/a.spec.ts", "");
		volume.mkdirSync("/test/src/shared", { recursive: true });
		volume.writeFileSync("/test/src/shared/x.spec-d.ts", "");
		mocks.resolveAllProjects.mockResolvedValue([
			makeResolvedProject({ displayName: "client", include: ["src/client/**/*.spec.ts"] }),
		]);

		await runMultiProjectAsync({
			cli: makeCli(),
			config,
			fileSystem,
			rawProjects: [makeProjectEntry("client")],
			seams,
		});

		expect(mocks.runTypecheck).toHaveBeenCalledWith(
			expect.objectContaining({
				files: expect.arrayContaining([expect.stringMatching(/x\.spec-d\.ts$/)]),
			}),
		);
	});

	it("should drop type test files matching a typecheck exclude glob", async () => {
		expect.assertions(2);

		const { config, fileSystem, volume } = setupDefaults({
			typecheck: { enabled: true, exclude: ["src/client/**/*.gen.spec-d.ts"] },
		});

		mocks.runTypecheck.mockResolvedValue(makeJestResult());
		volume.mkdirSync("/test/src/client", { recursive: true });
		volume.writeFileSync("/test/src/client/a.spec.ts", "");
		volume.writeFileSync("/test/src/client/a.spec-d.ts", "");
		volume.writeFileSync("/test/src/client/a.gen.spec-d.ts", "");
		mocks.resolveAllProjects.mockResolvedValue([
			makeResolvedProject({ displayName: "client", include: ["src/client/**/*.spec.ts"] }),
		]);

		await runMultiProjectAsync({
			cli: makeCli(),
			config,
			fileSystem,
			rawProjects: [makeProjectEntry("client")],
			seams,
		});

		const { files } = mocks.runTypecheck.mock.calls[0]![0];

		expect(files).toContain("src/client/a.spec-d.ts");
		expect(files).not.toContain("src/client/a.gen.spec-d.ts");
	});

	it("should not apply typecheck exclude to explicitly named positional files", async () => {
		expect.assertions(1);

		const { config, fileSystem, volume } = setupDefaults({
			typecheck: { enabled: true, exclude: ["src/client/**/*.spec-d.ts"] },
		});

		mocks.runTypecheck.mockResolvedValue(makeJestResult());
		volume.mkdirSync("/test/src/client", { recursive: true });
		volume.writeFileSync("/test/src/client/a.spec-d.ts", "");
		mocks.resolveAllProjects.mockResolvedValue([
			makeResolvedProject({ displayName: "client", include: ["src/client/**/*.spec.ts"] }),
		]);

		await runMultiProjectAsync({
			cli: makeCli({ files: ["src/client/a.spec-d.ts"] }),
			config,
			fileSystem,
			rawProjects: [makeProjectEntry("client")],
			seams,
		});

		expect(mocks.runTypecheck).toHaveBeenCalledWith(
			expect.objectContaining({
				files: expect.arrayContaining([expect.stringMatching(/a\.spec-d\.ts$/)]),
			}),
		);
	});

	it("should drop runtime test files matching a per-project exclude glob", async () => {
		expect.assertions(1);

		const { config, fileSystem, volume } = setupDefaults();

		volume.mkdirSync("/test/src/client", { recursive: true });
		volume.writeFileSync("/test/src/client/a.spec.ts", "");
		volume.writeFileSync("/test/src/client/a.gen.spec.ts", "");
		mocks.resolveAllProjects.mockResolvedValue([
			makeResolvedProject({
				displayName: "client",
				exclude: ["**/*.gen.spec.ts"],
				include: ["src/client/**/*.spec.ts"],
			}),
		]);

		await runMultiProjectAsync({
			cli: makeCli(),
			config,
			fileSystem,
			rawProjects: [makeProjectEntry("client")],
			seams,
		});

		const { projects } = mocks.runProjects.mock.calls[0]![0];

		expect(projects[0]!.testFiles).toStrictEqual(["src/client/a.spec.ts"]);
	});

	// AC #2: with coverage on, derivation must keep `-d` globs out of
	// `project.include`. `deriveCoverageFromIncludes` runs `inferSourceExtension`
	// over `project.include` — a leaked `*.spec-d.ts` would throw "Cannot infer
	// source extension", so completing the run proves the invariant holds.
	it("should run coverage with typecheck enabled without inferring a -d source extension", async () => {
		expect.assertions(2);

		const { config, fileSystem, volume } = setupDefaults({
			collectCoverage: true,
			typecheck: { enabled: true },
		});

		mocks.prepareCoverage.mockResolvedValue(fromAny(makeCoverageResult()));
		mocks.runTypecheck.mockResolvedValue(makeJestResult());
		volume.mkdirSync("/test/src/client", { recursive: true });
		volume.writeFileSync("/test/src/client/a.spec.ts", "");
		volume.writeFileSync("/test/src/client/a.spec-d.ts", "");
		mocks.resolveAllProjects.mockResolvedValue([
			makeResolvedProject({ displayName: "client", include: ["src/client/**/*.spec.ts"] }),
		]);

		const result = await runMultiProjectAsync({
			cli: makeCli(),
			config,
			fileSystem,
			rawProjects: [makeProjectEntry("client")],
			seams,
		});

		expect(result.mode).toBe("multi");
		expect(result.typecheckResult).toBeDefined();
	});

	it("should merge coverage data and source mappers across project results", async () => {
		expect.assertions(2);

		const { config, fileSystem, volume } = setupDefaults();
		seedProjectFiles(volume);

		mocks.runProjects.mockImplementation(async (input) => {
			return {
				backendTiming: { executionMs: 100, uploadMs: 50 },
				ranProjectIndices: allProjectIndices(input),
				results: input.projects.map((project) => {
					const tag = project.displayName!;
					return makeExecuteResult({
						coverageData: { [`${tag}.luau`]: { s: { "0": 1 } } },
						sourceMapper: {
							mapFailureWithLocations: (message) => {
								return {
									locations: [],
									message: `[${tag}] ${message}`,
								};
							},
							mapTestFileLine: () => {},
							resolveDisplayPath: (testFilePath) => testFilePath,
							resolveTestFilePath: () => {},
						},
					});
				}),
			};
		});

		const result = await runMultiProjectAsync({
			cli: makeCli(),
			config,
			fileSystem,
			rawProjects: [makeProjectEntry("client"), makeProjectEntry("server")],
			seams,
		});

		expect(result.merged.coverageData).toBeDefined();
		expect(result.merged.sourceMapper!.mapFailureWithLocations("hi").message).toContain("hi");
	});

	it("should merge per-test attribution across project results", async () => {
		expect.assertions(2);

		const { config, fileSystem, volume } = setupDefaults();
		seedProjectFiles(volume);

		mocks.runProjects.mockImplementation(async (input) => {
			return {
				backendTiming: { executionMs: 100, uploadMs: 50 },
				ranProjectIndices: allProjectIndices(input),
				results: input.projects.map((project) => {
					const tag = project.displayName!;
					return makeExecuteResult({
						attribution: {
							coveringTestIds: { "shared.luau": { "1": [tag] } },
							staticStatementIds: {},
							tests: [
								{
									testCaseId: tag,
									testFilePath: `${tag}.spec.luau`,
									testFileSourceHash: "h",
									testId: tag,
								},
							],
						},
					});
				}),
			};
		});

		const result = await runMultiProjectAsync({
			cli: makeCli(),
			config,
			fileSystem,
			rawProjects: [makeProjectEntry("client"), makeProjectEntry("server")],
			seams,
		});

		expect(result.merged.attribution!.tests).toHaveLength(2);
		expect(result.merged.attribution!.coveringTestIds["shared.luau"]).toStrictEqual({
			"1": ["client", "server"],
		});
	});

	it("should pass parallel for open-cloud backend and drop it for studio", async () => {
		expect.assertions(2);

		const { config, fileSystem, volume } = setupDefaults({ parallel: 2 });
		mocks.resolveBackend.mockResolvedValueOnce(makeBackend("open-cloud"));
		seedProjectFiles(volume);

		await runMultiProjectAsync({
			cli: makeCli(),
			config,
			fileSystem,
			rawProjects: [makeProjectEntry("client")],
			seams,
		});

		const openCloudCall = mocks.runProjects.mock.calls[0];

		expect(openCloudCall![0].parallel).toBe(2);

		mocks.runProjects.mockClear();
		mocks.resolveBackend.mockResolvedValueOnce(makeBackend("studio"));
		await runMultiProjectAsync({
			cli: makeCli(),
			config,
			fileSystem,
			rawProjects: [makeProjectEntry("client")],
			seams,
		});

		const studioCall = mocks.runProjects.mock.calls[0];

		expect(studioCall![0].parallel).toBeUndefined();
	});

	it("should pass the experimental VM count through to the backend", async () => {
		expect.assertions(1);

		const { config, fileSystem, volume } = setupDefaults({ experimentalVmParallel: 2 });
		seedProjectFiles(volume);

		await runMultiProjectAsync({
			cli: makeCli(),
			config,
			fileSystem,
			rawProjects: [makeProjectEntry("client"), makeProjectEntry("server")],
			seams,
		});

		expect(mocks.runProjects.mock.calls[0]![0].vmParallel).toBe(2);
	});

	it("should derive coverage paths via collectCoverageFrom passthrough when computing merged data", async () => {
		expect.assertions(1);

		const { config, fileSystem, volume } = setupDefaults();
		seedProjectFiles(volume);

		// Without coverageData on any project, merged.coverageData stays
		// undefined.
		const result = await runMultiProjectAsync({
			cli: makeCli(),
			config,
			fileSystem,
			rawProjects: [makeProjectEntry("client")],
			seams,
		});

		expect(result.merged.coverageData).toBeUndefined();
	});

	// The empty-set check is hoisted ahead of the backend, and staging now sits
	// behind the backend — so an empty run resolves nothing, writes nothing and
	// reports no staging time, where before it swept and generated its stubs
	// first. A consequence of the reorder the binary-input path needed, and the
	// one behaviour it changed for a run with no tests.
	it("should resolve no backend and stage nothing when no jobs were produced", async () => {
		expect.assertions(4);

		const { config, fileSystem, volume } = setupDefaults();
		// No project files seeded — the plan is empty.

		const result = await runMultiProjectAsync({
			cli: makeCli({ passWithNoTests: true }),
			config: { ...config, passWithNoTests: true },
			fileSystem,
			rawProjects: [makeProjectEntry("client")],
			seams,
		});

		expect(mocks.resolveBackend).not.toHaveBeenCalled();
		expect(volume.existsSync(cacheStubPath("out/client"))).toBeFalse();
		expect(result.stagingMs).toBe(0);
		expect(result.projectResults).toHaveLength(0);
	});

	// The studio-cli backend exposes no `close` hook. `makeBackend` always
	// defines one, so these two pin the optional-chain at each call site.
	it("should tolerate a backend without a close hook", async () => {
		expect.assertions(1);

		const { config, fileSystem, volume } = setupDefaults();
		mocks.resolveBackend.mockResolvedValueOnce({
			kind: "studio",
			runTestsAsync: vi.fn<Backend["runTestsAsync"]>(),
		});
		mocks.resolveAllProjects.mockResolvedValue([
			makeResolvedProject({ displayName: "client" }),
		]);
		seedProjectFiles(volume);

		const result = await runMultiProjectAsync({
			cli: makeCli(),
			config,
			fileSystem,
			rawProjects: [makeProjectEntry("client")],
			seams,
		});

		expect(result.projectResults).toHaveLength(1);
	});

	it("should tolerate a backend without a close hook when the run throws", async () => {
		expect.assertions(1);

		const { config, fileSystem, volume } = setupDefaults();
		mocks.resolveBackend.mockResolvedValueOnce({
			kind: "studio",
			runTestsAsync: vi.fn<Backend["runTestsAsync"]>(),
		});
		const error = new Error("dispatch failed");
		mocks.runProjects.mockRejectedValueOnce(error);
		seedProjectFiles(volume);

		await expect(
			runMultiProjectAsync({
				cli: makeCli(),
				config,
				fileSystem,
				rawProjects: [makeProjectEntry("client")],
				seams,
			}),
		).rejects.toBe(error);
	});

	it("should resolve setupFilesAfterEnv paths via the setup resolver", async () => {
		expect.assertions(1);

		const { config, fileSystem, volume } = setupDefaults();
		mocks.createSetupResolver.mockReturnValue((input) => `resolved:${input}`);
		mocks.resolveAllProjects.mockResolvedValue([
			makeResolvedProject({
				config: makeConfig({ setupFilesAfterEnv: ["./post.ts"] }),
				displayName: "client",
			}),
		]);
		seedProjectFiles(volume);

		await runMultiProjectAsync({
			cli: makeCli(),
			config,
			fileSystem,
			rawProjects: [makeProjectEntry("client")],
			seams,
		});

		const { projects } = mocks.runProjects.mock.calls[0]![0];

		expect(projects[0]!.config.setupFilesAfterEnv).toStrictEqual(["resolved:./post.ts"]);
	});

	it("should narrow project config by CLI files for Luau-side execution", async () => {
		expect.assertions(1);

		const { config, fileSystem, volume } = setupDefaults();
		seedProjectFiles(volume);

		await runMultiProjectAsync({
			cli: makeCli({ files: ["src/client/a.spec.ts"] }),
			config,
			fileSystem,
			rawProjects: [makeProjectEntry("client")],
			seams,
		});

		const { projects } = mocks.runProjects.mock.calls[0]![0];

		expect(projects[0]!.config.testPathPattern).toBe("(a\\.spec)");
	});

	// Regression: a basename pattern runs every namesake test file, so a repo
	// naming each test `index.spec.ts` cannot run just one. The forwarded pattern
	// carries the path below the Rojo mount instead.
	it("should narrow to the instance sub-path so a namesake file is left out", async () => {
		expect.assertions(1);

		const { config, fileSystem, volume } = setupDefaults();
		seedProjectFiles(volume);
		seedIndexNamesakes(volume);

		await runMultiProjectAsync({
			cli: makeCli({ files: ["src/client/a/index.spec.ts"] }),
			config,
			fileSystem,
			rawProjects: [makeProjectEntry("client")],
			seams,
		});

		const { projects } = mocks.runProjects.mock.calls[0]![0];

		expect(projects[0]!.config.testPathPattern).toBe("(client/a/init\\.spec)");
	});

	it("should forward a basename pattern when --testPathPattern is a filesystem path", async () => {
		expect.assertions(1);

		const { config, fileSystem, volume } = setupDefaults();
		mocks.resolveAllProjects.mockResolvedValue([
			makeResolvedProject({
				config: makeConfig({ testPathPattern: "src/client/a.spec" }),
				displayName: "client",
				outDir: "out/client",
			}),
		]);
		seedProjectFiles(volume);

		await runMultiProjectAsync({
			cli: makeCli({ testPathPattern: "src/client/a.spec" }),
			config: { ...config, testPathPattern: "src/client/a.spec" },
			fileSystem,
			rawProjects: [makeProjectEntry("client")],
			seams,
		});

		const { projects } = mocks.runProjects.mock.calls[0]![0];

		expect(projects[0]!.config.testPathPattern).toBe("(a\\.spec)");
	});

	it("should call filterProjectsByFiles with cli files when --project is absent", async () => {
		expect.assertions(1);

		const { config, fileSystem, volume } = setupDefaults();
		seedProjectFiles(volume);

		const result = await runMultiProjectAsync({
			cli: makeCli({ files: ["src/server/b.spec.ts"] }),
			config,
			fileSystem,
			rawProjects: [makeProjectEntry("client"), makeProjectEntry("server")],
			seams,
		});

		expect(result.projectResults.map((entry) => entry.displayName)).toStrictEqual(["server"]);
	});

	it("should feed each project only the cli files filterProjectsByFiles paired with it", async () => {
		expect.assertions(2);

		const { config, fileSystem, volume } = setupDefaults();
		seedProjectFiles(volume);

		await runMultiProjectAsync({
			cli: makeCli({ files: ["src/client/a.spec.ts", "src/server/b.spec.ts"] }),
			config,
			fileSystem,
			rawProjects: [makeProjectEntry("client"), makeProjectEntry("server")],
			seams,
		});

		const { projects } = mocks.runProjects.mock.calls[0]![0];

		expect(projects[0]!.config.testPathPattern).toBe("(a\\.spec)");
		expect(projects[1]!.config.testPathPattern).toBe("(b\\.spec)");
	});

	it("should resolve a relative cli file against rootDir before matching", async () => {
		expect.assertions(1);

		const { config, fileSystem, volume } = setupDefaults();
		seedProjectFiles(volume);

		const result = await runMultiProjectAsync({
			cli: makeCli({ files: ["src/server/b.spec.ts"] }),
			config,
			fileSystem,
			rawProjects: [makeProjectEntry("client"), makeProjectEntry("server")],
			seams,
		});

		expect(result.projectResults.map((entry) => entry.displayName)).toStrictEqual(["server"]);
	});

	it("should propagate filterProjectsByFiles errors when no project owns the file", async () => {
		expect.assertions(1);

		const { config, fileSystem, volume } = setupDefaults();
		seedProjectFiles(volume);

		await expect(
			runMultiProjectAsync({
				cli: makeCli({ files: ["src/shared/x.spec.ts"] }),
				config,
				fileSystem,
				rawProjects: [makeProjectEntry("client"), makeProjectEntry("server")],
				seams,
			}),
		).rejects.toThrow(/No project contains the requested file/);
	});

	it("should skip filterProjectsByFiles when --project is set even if files are passed", async () => {
		expect.assertions(2);

		const { config, fileSystem, volume } = setupDefaults();
		seedProjectFiles(volume);

		const result = await runMultiProjectAsync({
			cli: makeCli({ files: ["src/server/b.spec.ts"], project: ["client"] }),
			config,
			fileSystem,
			rawProjects: [makeProjectEntry("client"), makeProjectEntry("server")],
			seams,
		});

		expect(result.projectResults).toHaveLength(1);
		expect(result.projectResults.map((entry) => entry.displayName)).toStrictEqual(["client"]);
	});

	it("should skip filterProjectsByFiles when no cli files are passed", async () => {
		expect.assertions(1);

		const { config, fileSystem, volume } = setupDefaults();
		seedProjectFiles(volume);

		const bare = await runMultiProjectAsync({
			cli: makeCli(),
			config,
			fileSystem,
			rawProjects: [makeProjectEntry("client"), makeProjectEntry("server")],
			seams,
		});
		const empty = await runMultiProjectAsync({
			cli: makeCli({ files: [] }),
			config,
			fileSystem,
			rawProjects: [makeProjectEntry("client"), makeProjectEntry("server")],
			seams,
		});

		expect([bare.projectResults.length, empty.projectResults.length]).toStrictEqual([2, 2]);
	});

	it("should resolve setupFiles per-project via discovery helper", async () => {
		expect.assertions(1);

		const { config, fileSystem, volume } = setupDefaults();
		mocks.resolveAllProjects.mockResolvedValue([
			makeResolvedProject({
				config: makeConfig({ setupFiles: ["./setup.ts"] }),
				displayName: "client",
				include: ["src/client/**/*.spec.ts"],
			}),
		]);
		mocks.createSetupResolver.mockReturnValue((input) => `resolved:${input}`);
		seedProjectFiles(volume);

		await runMultiProjectAsync({
			cli: makeCli(),
			config,
			fileSystem,
			rawProjects: [makeProjectEntry("client")],
			seams,
		});

		const project = mocks.runProjects.mock.calls[0]![0].projects[0];

		expect(project!.config.setupFiles).toStrictEqual(["resolved:./setup.ts"]);
	});

	it("should preserve backend errors and still close the backend", async () => {
		expect.assertions(2);

		const { config, fileSystem, volume } = setupDefaults();
		const backend = makeBackend("studio");
		mocks.resolveBackend.mockResolvedValueOnce(backend);
		seedProjectFiles(volume);
		const error = new Error("backend failed");
		mocks.runProjects.mockRejectedValueOnce(error);

		await expect(
			runMultiProjectAsync({
				cli: makeCli(),
				config,
				fileSystem,
				rawProjects: [makeProjectEntry("client")],
				seams,
			}),
		).rejects.toBe(error);
		expect(backend.closeAsync).toHaveBeenCalledOnce();
	});

	it("should emit a stderr notice listing the leftover stubs cleaned", async () => {
		expect.assertions(2);

		const { config, fileSystem, volume } = setupDefaults();
		const leftover = seedLeftoverStubs(volume);
		const stderr = vi.spyOn(process.stderr, "write").mockReturnValue(true);
		seedProjectFiles(volume);

		await runMultiProjectAsync({
			cli: makeCli(),
			config,
			fileSystem,
			rawProjects: [makeProjectEntry("client")],
			seams,
		});

		expect(stderr).toHaveBeenCalledOnce();

		const written = stderr.mock.calls[0]![0];
		assert(typeof written === "string", "stderr.write called with non-string");

		expect(written).toBe(
			`jest-roblox: cleaned 2 leftover stub(s):\n  ${leftover[0]}\n  ${leftover[1]}\n`,
		);
	});

	it("should not emit a leftover-stub notice when cleanup finds nothing", async () => {
		expect.assertions(1);

		const { config, fileSystem, volume } = setupDefaults();
		const stderr = vi.spyOn(process.stderr, "write").mockReturnValue(true);
		seedProjectFiles(volume);

		await runMultiProjectAsync({
			cli: makeCli(),
			config,
			fileSystem,
			rawProjects: [makeProjectEntry("client")],
			seams,
		});

		expect(stderr).not.toHaveBeenCalled();
	});

	it("should carry every mount without a user-authored config as a runtime injection path", async () => {
		expect.assertions(2);

		const { config, fileSystem, volume } = setupDefaults();
		seedProjectFiles(volume);

		await runMultiProjectAsync({
			cli: makeCli(),
			config,
			fileSystem,
			rawProjects: [makeProjectEntry("client")],
			seams,
		});

		const jobs = mocks.runProjects.mock.calls[0]![0].projects;

		expect(jobs[0]!.runtimeInjectionPaths).toStrictEqual(["ReplicatedStorage/client"]);
		expect(jobs[1]!.runtimeInjectionPaths).toStrictEqual(["ServerScriptService/server"]);
	});

	it("should skip stubMounts and runtimeInjectionPaths for mounts with user-authored configs", async () => {
		expect.assertions(4);

		// Whole-place: the split would take both mounts into the bundle, and
		// what this case pins is what synthesis put inside them.
		const { config, fileSystem, volume } = setupDefaults({ binaryInput: false });
		mocks.resolveBackend.mockResolvedValueOnce(makeBackend("open-cloud"));
		seedUserAuthoredConfigs(volume);
		seedProjectFiles(volume);

		await runMultiProjectAsync({
			cli: makeCli(),
			config,
			fileSystem,
			rawProjects: [makeProjectEntry("client")],
			seams,
		});

		const synth = writtenSynthProject(volume);

		expect(synth.tree).toStrictEqual({
			$className: "DataModel",
			ReplicatedStorage: { client: { $path: "../../out/client" } },
			ServerScriptService: { server: { $path: "../../out/server" } },
		});

		// `runtimeInjectionPaths` on the job is also empty for the same reason.
		const jobs = mocks.runProjects.mock.calls[0]![0].projects;

		expect(jobs[0]!.runtimeInjectionPaths).toStrictEqual([]);
		expect(volume.existsSync(cacheStubPath("out/client"))).toBeFalse();
		expect(volume.existsSync(cacheStubPath("out/server"))).toBeFalse();
	});
});
