import { type } from "arktype";
import fs from "node:fs";
import path from "node:path";

const manifestSchema = type({ version: "string" });

/**
 * Write the package's release version into the plugin source tree, so a
 * connected plugin can name itself in the CLI's handshake.
 *
 * The `.rbxm` carries no metadata of its own, and a user running several
 * installed copies has no way to tell them apart otherwise — a protocol number
 * says a copy is stale, not which file to delete. Generated rather than
 * committed because the release tool writes the version to `package.json`
 * alone, so a checked-in copy would be stale for the length of every release
 * commit.
 */
export function stampPluginVersion(packageRoot: string): string {
	const packageJsonPath = path.join(packageRoot, "package.json");
	const { version } = manifestSchema.assert(JSON.parse(fs.readFileSync(packageJsonPath, "utf8")));

	const target = path.join(packageRoot, "plugin", "src", "version.luau");
	fs.writeFileSync(
		target,
		`--!strict\n-- Generated by scripts/stamp-plugin-version.ts. Do not edit.\nreturn "${version}"\n`,
	);

	return version;
}
