// Build the official Luau parser to wasm and embed it as a base64 TypeScript
// module (src/luau-parser-wasm.ts) so every consumer bundle — ESM, CJS, SEA
// executable — carries the parser without runtime asset resolution.
//
// Reproducibility contract: with the pinned emsdk and Luau versions below, the
// output is byte-identical across machines. CI rebuilds and fails on any diff
// against the committed module (see wasm-verify in ci.yaml), so a Luau or
// emsdk bump must rerun this script and commit the result.
//
// Requirements: `em++` on PATH (or $EMXX pointing at it) and `git`.
// Usage: node build-wasm.ts [luau-source-dir]
//   With no argument, clones Luau at the pinned tag into a temp dir.

import { execFileSync } from "node:child_process";
import crypto from "node:crypto";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import process from "node:process";

const LUAU_TAG = "0.731";
const EMSDK_VERSION = "6.0.8";

const EMCC_VERSION = /^emcc \D*(\d+\.\d+\.\d+)/;

const WASM_DIRECTORY = import.meta.dirname;
const WASM_ARTIFACT = "luau-parser.wasm";
const EMBEDDED_MODULE = path.join(WASM_DIRECTORY, "..", "src", "luau-parser-wasm.ts");

const EMXX = process.env["EMXX"] ?? "em++";

interface LuauCheckout {
	directory: string;
	/**
	 * The temp root to remove afterwards, absent when the caller supplied a
	 * checkout.
	 */
	temporaryRoot: string | undefined;
}

function capture(command: string, args: Array<string>): string {
	return execFileSync(command, args, { encoding: "utf8", windowsHide: true });
}

function assertEmscriptenVersion(): void {
	const [banner = ""] = capture(EMXX, ["--version"]).split("\n", 1);
	const [, found] = EMCC_VERSION.exec(banner) ?? [];
	if (found !== EMSDK_VERSION) {
		throw new Error(`emscripten ${EMSDK_VERSION} required, found ${found ?? banner}`);
	}
}

function checkoutLuau(): LuauCheckout {
	const provided = process.argv[2];
	if (provided !== undefined) {
		return { directory: provided, temporaryRoot: undefined };
	}

	const temporaryRoot = fs.mkdtempSync(path.join(os.tmpdir(), "luau-"));
	const directory = path.join(temporaryRoot, "luau");
	execFileSync(
		"git",
		[
			"clone",
			"--depth",
			"1",
			"--branch",
			LUAU_TAG,
			"https://github.com/luau-lang/luau",
			directory,
		],
		{ stdio: "inherit", windowsHide: true },
	);

	return { directory, temporaryRoot };
}

// readdir order is filesystem-dependent, and link order decides the layout of
// the wasm. Sorting is what keeps the output byte-identical across machines.
function astSources(luauSource: string): Array<string> {
	const astSource = path.join(luauSource, "Ast", "src");
	return fs
		.readdirSync(astSource)
		.filter((entry) => entry.endsWith(".cpp"))
		.sort()
		.map((entry) => path.join(astSource, entry));
}

function compile(luauSource: string): void {
	execFileSync(
		EMXX,
		[
			// -fwasm-exceptions: the parser reports errors by throwing
			// ParseError; native wasm EH needs Node 24+, which the workspace
			// already requires.
			"-O2",
			"-std=c++17",
			"-DNDEBUG",
			"-fwasm-exceptions",
			`-I${path.join(luauSource, "Ast", "include")}`,
			`-I${path.join(luauSource, "Common", "include")}`,
			`-I${path.join(luauSource, "Analysis", "include")}`,
			...astSources(luauSource),
			path.join(luauSource, "Analysis", "src", "AstJsonEncoder.cpp"),
			path.join(luauSource, "Common", "src", "StringUtils.cpp"),
			"wrapper.cpp",
			// --no-entry + .wasm output: wasm-only build, no JS glue — the
			// TypeScript loader in src/parser.ts provides the two runtime
			// imports itself.
			"--no-entry",
			"-sALLOW_MEMORY_GROWTH=1",
			// Parse and JSON-encode recursion on deeply nested sources
			// outgrows the 64 KB default.
			"-sSTACK_SIZE=1048576",
			"-sEXPORTED_FUNCTIONS=_parse_to_json,_free_result,_malloc,_free",
			"-o",
			WASM_ARTIFACT,
		],
		{ cwd: WASM_DIRECTORY, stdio: "inherit", windowsHide: true },
	);
}

function embed(wasmPath: string): void {
	const header = [
		"// Generated by wasm/build-wasm.ts — do not edit.",
		"// The official Luau parser (see wasm/wrapper.cpp), embedded so every",
		"// consumer bundle carries it without runtime asset resolution.",
		"",
		"export const luauParserWasmBase64 =",
	].join("\n");

	const base64 = fs.readFileSync(wasmPath).toString("base64");
	fs.writeFileSync(EMBEDDED_MODULE, `${header}\n\t"${base64}";\n`);
}

function reportDigest(filePath: string, label: string): void {
	const digest = crypto.createHash("sha256").update(fs.readFileSync(filePath)).digest("hex");
	process.stdout.write(`${digest}  ${label}\n`);
}

function build(): void {
	assertEmscriptenVersion();

	const luau = checkoutLuau();
	try {
		const tag = capture("git", ["-C", luau.directory, "describe", "--tags"]).trim();
		if (tag !== LUAU_TAG) {
			throw new Error(`Luau checkout is ${tag}, pin is ${LUAU_TAG}`);
		}

		compile(luau.directory);
	} finally {
		if (luau.temporaryRoot !== undefined) {
			fs.rmSync(luau.temporaryRoot, { force: true, recursive: true });
		}
	}

	const wasmPath = path.join(WASM_DIRECTORY, WASM_ARTIFACT);
	embed(wasmPath);
	reportDigest(wasmPath, WASM_ARTIFACT);
	reportDigest(EMBEDDED_MODULE, "../src/luau-parser-wasm.ts");
	fs.rmSync(wasmPath);
}

try {
	build();
} catch (err) {
	console.error(`error: ${err instanceof Error ? err.message : String(err)}`);
	process.exit(1);
}
